/**
 * Trace fixture/recording path utilities for WDIO tests.
 *
 * Traces are stored in two locations:
 * - `test/traces/<name>/`   — dynamically recorded by scripts/record-test-traces.sh
 * - `test/fixtures/<name>/` — prepared fixtures generated by scripts/prepare-*.sh
 *
 * The WDIO_TRACE_BASE and WDIO_FIXTURE_BASE env vars allow CI to override paths.
 */
import path from 'path'
import fs from 'fs'

const REPO_ROOT = path.resolve(__dirname, '..', '..', '..')

/** Resolve path to a dynamically recorded trace directory. */
export function resolveTracePath(traceName: string): string {
  const base = process.env.WDIO_TRACE_BASE || path.join(REPO_ROOT, 'test', 'traces')
  return path.resolve(base, traceName)
}

/** Resolve path to a committed fixture directory. */
export function resolveFixturePath(fixtureName: string): string {
  const base = process.env.WDIO_FIXTURE_BASE || path.join(REPO_ROOT, 'test', 'fixtures')
  return path.resolve(base, fixtureName)
}

/** Check whether a trace directory contains the minimum required files. */
export function traceExists(traceName: string): boolean {
  const dir = resolveTracePath(traceName)
  return hasTraceFiles(dir)
}

/** Check whether a fixture directory contains the minimum required files. */
export function fixtureExists(fixtureName: string): boolean {
  const dir = resolveFixturePath(fixtureName)
  return hasTraceFiles(dir)
}

/** Check whether the directory contains a non-empty `.ct` CTFS container. */
function hasCtfsContainer(dir: string): boolean {
  try {
    const entries = fs.readdirSync(dir)
    for (const entry of entries) {
      if (!entry.endsWith('.ct')) continue
      const stat = fs.statSync(path.join(dir, entry))
      if (stat.isFile() && stat.size > 0) return true
    }
  } catch {
    // ignore — falls through to false
  }
  return false
}

/**
 * Check whether a directory contains valid trace files.
 *
 * Three recorder output shapes are recognised:
 *  - CTFS containers: one or more `.ct` files at the bundle root. This is the
 *    canonical, recorder-convention output for the materialized-trace
 *    languages (Python, Ruby, JavaScript, the blockchain recorders, BEAM …).
 *    The Nim CTFS writer names the container after the recorded program
 *    (e.g. `main.ct`), so any non-empty `.ct` file counts. The db-backend
 *    auto-detects the container in the folder via `find_ct_file_in_dir`.
 *  - rr/native traces: `ct-native-replay` writes `trace_db_metadata.json`
 *    plus a packed recording.
 *  - Legacy DB traces: `trace_metadata.json` + `trace.json`/`trace.bin`.
 *
 * The CTFS check is performed first and independently — a recorder that
 * emits a CTFS-only bundle (no JSON metadata sidecar, which is the current
 * convention) must still be recognised as a valid trace.
 */
function hasTraceFiles(dir: string): boolean {
  if (!fs.existsSync(dir)) return false
  // CTFS containers are the canonical recorder output and carry their own
  // metadata inside `meta.dat`; no JSON sidecar is required.
  if (hasCtfsContainer(dir)) return true
  // rr-based traces: ct-native-replay writes trace_db_metadata.json.
  if (fs.existsSync(path.join(dir, 'trace_db_metadata.json'))) return true
  // Legacy DB-based traces: trace_metadata.json + a trace data file.
  if (fs.existsSync(path.join(dir, 'trace_metadata.json')) &&
      (fs.existsSync(path.join(dir, 'trace.json')) ||
       fs.existsSync(path.join(dir, 'trace.bin')))) {
    return true
  }
  return false
}
