/**
 * Trace fixture/recording path utilities for WDIO tests.
 *
 * Traces are stored in two locations:
 * - `test/traces/<name>/`   — dynamically recorded by scripts/record-test-traces.sh
 * - `test/fixtures/<name>/` — prepared fixtures generated by scripts/prepare-*.sh
 *
 * The WDIO_TRACE_BASE and WDIO_FIXTURE_BASE env vars allow CI to override paths.
 */
import path from 'path'
import fs from 'fs'

const REPO_ROOT = path.resolve(__dirname, '..', '..', '..')

/** Resolve path to a dynamically recorded trace directory. */
export function resolveTracePath(traceName: string): string {
  const base = process.env.WDIO_TRACE_BASE || path.join(REPO_ROOT, 'test', 'traces')
  return path.resolve(base, traceName)
}

/** Resolve path to a committed fixture directory. */
export function resolveFixturePath(fixtureName: string): string {
  const base = process.env.WDIO_FIXTURE_BASE || path.join(REPO_ROOT, 'test', 'fixtures')
  return path.resolve(base, fixtureName)
}

/** Check whether a trace directory contains the minimum required files. */
export function traceExists(traceName: string): boolean {
  const dir = resolveTracePath(traceName)
  return hasTraceFiles(dir)
}

/** Check whether a fixture directory contains the minimum required files. */
export function fixtureExists(fixtureName: string): boolean {
  const dir = resolveFixturePath(fixtureName)
  return hasTraceFiles(dir)
}

/**
 * Check whether a directory contains valid trace files.
 *
 * DB-based traces produce trace_metadata.json + trace.json/trace.bin/*.ct.
 * rr-based traces (Rust, C, Go, Nim) produce trace_db_metadata.json + packed rr data.
 * CTFS-based traces (BEAM Elixir/Erlang, M15+) produce trace_metadata.json
 * plus one or more `.ct` container files at the bundle root.
 */
function hasTraceFiles(dir: string): boolean {
  if (!fs.existsSync(dir)) return false
  // DB-based traces: trace_metadata.json is the primary indicator.
  const hasDbMetadata = fs.existsSync(path.join(dir, 'trace_metadata.json'))
  // rr-based traces: ct-native-replay writes trace_db_metadata.json.
  const hasRrMetadata = fs.existsSync(path.join(dir, 'trace_db_metadata.json'))
  if (!hasDbMetadata && !hasRrMetadata) return false
  // For DB-based traces, also require a trace data file.
  // rr-based traces store data differently (packed rr recording), so
  // trace_db_metadata.json alone is sufficient.
  if (hasRrMetadata) return true
  if (fs.existsSync(path.join(dir, 'trace.json')) ||
      fs.existsSync(path.join(dir, 'trace.bin'))) {
    return true
  }
  // CTFS-based traces (BEAM): a non-empty .ct file at the bundle root.
  // The codetracer-beam-recorder writes either erl.ct or mix.ct depending
  // on the runner; we accept any .ct file as evidence the recorder
  // produced a real bundle. Empty .ct files are rejected so half-recorded
  // bundles don't quietly satisfy the predicate.
  try {
    const entries = fs.readdirSync(dir)
    for (const entry of entries) {
      if (!entry.endsWith('.ct')) continue
      const stat = fs.statSync(path.join(dir, entry))
      if (stat.isFile() && stat.size > 0) return true
    }
  } catch {
    // ignore — falls through to false
  }
  return false
}
