import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-aiken-fixture.sh.
// It records the Aiken flow_test.ak program which:
//   - Performs UPLC CEK machine operations
//   - Exercises the Aiken/Cardano recorder with source mapping
defineLanguageSmokeTests({
  language: 'Aiken',
  traceName: 'aiken-flow-test',
  expectedFileName: 'flow_test.ak',
  calltraceFunction: 'compute',
  variableName: 'a',
  langId: 'Aiken',
})
