import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-cadence-fixture.sh.
// It records the Cadence flow_test.cdc program which:
//   - Performs resource-oriented operations
//   - Exercises the Cadence/Flow VM tracer
defineLanguageSmokeTests({
  language: 'Cadence',
  traceName: 'cadence-flow-test',
  expectedFileName: 'flow_test.cdc',
  calltraceFunction: 'compute',
  variableName: 'a',
  langId: 'Cadence',
})
