import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-cairo-fixture.sh.
// It records the Cairo flow_test.cairo program which:
//   - Performs felt-based arithmetic operations
//   - Exercises the Cairo VM execution path with Sierra debug info
defineLanguageSmokeTests({
  language: 'Cairo',
  traceName: 'cairo-flow-test',
  expectedFileName: 'flow_test.cairo',
  calltraceFunction: 'compute',
  variableName: 'a',
  langId: 'Cairo',
})
