import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-circom-fixture.sh.
// It records the Circom flow_test.circom circuit which:
//   - Performs signal constraint operations
//   - Exercises the Circom witness generation and Wasm tracer
defineLanguageSmokeTests({
  language: 'Circom',
  traceName: 'circom-flow-test',
  expectedFileName: 'flow_test.circom',
  calltraceFunction: 'compute',
  variableName: 'a',
  langId: 'Circom',
})
