/**
 * VS Code WDIO smoke tests for Elixir BEAM traces.
 *
 * Part of M15 (UI and VS Code Smoke Integration). Companion to
 * smoke/erlang.e2e.ts. The fixture is generated by the recorder-owned
 * scripts/prepare-beam-fixtures.sh — see scripts/record-test-traces.sh for
 * how `npm run test:wdio` populates `test/traces/elixir-canonical-flow/`.
 *
 * Per the M15 plan decision: regenerate from source in CI rather than store
 * goldens, so this spec assumes record-test-traces.sh ran first and the
 * trace already exists. If it doesn't, defineLanguageSmokeTests skips with a
 * loud diagnostic — the recorder-owned no-silent-skip guard
 * (verify-beam-fixture-generation-no-silent-skip.sh) ensures the script
 * itself fails loudly when prerequisites are missing.
 */
import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

defineLanguageSmokeTests({
  language: 'Elixir',
  // Recorded by codetracer-beam-recorder/scripts/prepare-beam-fixtures.sh
  // into <repo>/test/traces/elixir-canonical-flow.
  traceName: 'elixir-canonical-flow',
  expectedFileName: 'canonical_flow.ex',
  // The canonical_flow program defines `compute/0` (the canonical body) and
  // `main/0` (the runner). Either is reachable from the calltrace; we pick
  // the body so it doesn't drift if `main` ever gets renamed.
  calltraceFunction: 'compute',
  // Elixir local variables are lowercase by convention.
  variableName: 'final_result',
  langId: 'Elixir',
  // canonical_flow prints "94" via IO.puts/1.
  terminalText: '94',
  // The Elixir BEAM recorder is materialized (db-backend), not rr — so the
  // full locals payload is available and we don't need response-only mode.
  //
  // The trace starts at the top of the file; ``main/0`` (the runner) is
  // recorded at ``depth=0`` and ``compute/0`` at ``depth=1``.  ``final_result``
  // is a ``compute/0`` local — it only enters scope at line 9, ``inside`` the
  // compute body.  A plain step-over from the entry skips over the
  // ``result = compute()`` call (DAP semantics for ``next``) and lands at
  // line 16 of main/0 where only the wrapper's ``result`` rebinding is in
  // scope.  Use step-IN to enter compute, then step over the 4 intermediate
  // ``let``-bindings (``a``, ``b``, ``sum_val``, ``doubled``) so the locals
  // query at line 9 sees ``final_result`` bound to 94.  Mirrors the erlang
  // counterpart spec.
  useStepIn: true,
  extraStepsForLocals: 4,
})
