/**
 * Elixir canonical trace smoke tests for the CodeTracer VS Code extension.
 *
 * The fixture is generated by scripts/prepare-elixir-fixture.sh, which
 * delegates to the recorder-owned generator and records
 * codetracer-elixir-recorder/test-programs/elixir/canonical_flow.
 */
import childProcess from 'child_process'
import path from 'path'
import { expect } from '@wdio/globals'
import { DebugSession, EditorPane, ExtensionState } from '../../page-objects'
import {
  assertCalltraceContains,
  assertEditorLoadsFile,
  assertEventsPopulated,
  assertSessionStarts,
  assertStepWorks,
  assertTerminalContains,
  assertThreadsExist,
} from '../../helpers/language-smoke-helpers'
import { captureFullDiagnostics, screenshot, writeDiag } from '../../helpers/diagnostics'
import { fixtureExists, resolveFixturePath } from '../../helpers/trace-utils'

const TRACE_NAME = 'elixir-canonical-flow'
const EXPECTED_FILE = 'canonical_flow.ex'
const LANG_ID = 'Elixir'
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..', '..')

const session = new DebugSession()
const editor = new EditorPane()
const ext = new ExtensionState()

function prepareFixture(traceDir: string): void {
  const script = path.join(REPO_ROOT, 'scripts', 'prepare-elixir-fixture.sh')
  const result = childProcess.spawnSync(script, [traceDir], {
    cwd: REPO_ROOT,
    encoding: 'utf-8',
    stdio: 'pipe',
    env: {
      ...process.env,
      FORCE: process.env.CI ? '1' : process.env.FORCE ?? '0',
      TMPDIR: process.env.TMPDIR ?? path.join(REPO_ROOT, '.tmp'),
    },
    timeout: 120_000,
  })

  if (result.error || result.status !== 0) {
    throw new Error(
      `Elixir fixture preparation failed: error=${result.error}; status=${result.status}\n` +
      `stdout:\n${result.stdout}\nstderr:\n${result.stderr}`,
    )
  }
}

describe('CodeTracer Extension - Elixir Smoke Test', () => {
  let traceDir: string

  before(function () {
    traceDir = resolveFixturePath(TRACE_NAME)
    if (!fixtureExists(TRACE_NAME) || process.env.CI || process.env.FORCE === '1') {
      prepareFixture(traceDir)
    }
    if (!fixtureExists(TRACE_NAME)) {
      throw new Error(`Elixir smoke fixture was not generated at ${traceDir}`)
    }
  })

  afterEach(async function () {
    const testName = this.currentTest?.title?.replace(/[^a-zA-Z0-9_-]+/g, '-').substring(0, 50) ?? 'unknown'
    if (this.currentTest?.state === 'failed') {
      console.log(`[diag] Test failed: ${this.currentTest.title}`)
      await captureFullDiagnostics(`elixir-FAIL-${testName}`)
    }
    await screenshot(`elixir-${testName}`)
  })

  it('e2e_wdio_elixir_trace_smoke', async () => {
    await ext.ensureActivated()
    await assertSessionStarts(session, traceDir)

    const location = await session.currentLocation()
    console.log('[Elixir] Initial location:', JSON.stringify(location))
    writeDiag('elixir-session-start.json', { location })

    await assertEditorLoadsFile(editor, EXPECTED_FILE)
    const text = await editor.getText()
    expect(text).toContain('def compute do')
    expect(text).toContain('final_result = doubled + a')

    await assertThreadsExist(session)
    await assertEventsPopulated(session)
    await assertCalltraceContains(session, 'CanonicalFlow')
    await assertStepWorks(session, true)

    let dataStr = ''
    for (let i = 0; i < 10; i++) {
      const result = await session.loadLocals({ lang: LANG_ID, countBudget: 100, depthLimit: 3 })
      expect(result.ok).toBe(true)
      dataStr = JSON.stringify(result.data ?? {})
      writeDiag('elixir-locals.json', result.data ?? result.error)
      if (dataStr.includes('final_result') && dataStr.includes('94')) {
        break
      }
      await session.stepOver(750)
    }

    for (const expected of ['a', 'b', 'sum_val', 'doubled', 'final_result', '94']) {
      expect(dataStr).toContain(expected)
    }

    await assertTerminalContains(session, '94')
  })

  after(async () => {
    await captureFullDiagnostics('elixir-final')
    try { await session.removeAllBreakpoints() } catch { /* ignore */ }
    try { await session.stop() } catch { /* ignore */ }
  })
})
