/**
 * VS Code WDIO smoke tests for Erlang BEAM traces.
 *
 * Companion to smoke/elixir.e2e.ts. Erlang variables are capitalized by
 * language convention — the recorder's manifest carries the language so the
 * trace reader preserves the original casing, and the smoke assertions here
 * use the canonical Erlang names (`A`, `SumVal`, `FinalResult`).
 *
 * The fixture is generated by codetracer-beam-recorder/scripts/prepare-beam-
 * fixtures.sh and lives at `test/traces/erlang-canonical-flow/`. See
 * scripts/record-test-traces.sh for the WDIO-side wiring.
 */
import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

defineLanguageSmokeTests({
  language: 'Erlang',
  // Recorded by codetracer-beam-recorder/scripts/prepare-beam-fixtures.sh
  // into <repo>/test/traces/erlang-canonical-flow.
  traceName: 'erlang-canonical-flow',
  expectedFileName: 'canonical_flow.erl',
  // Calltrace contains entries like `canonical_flow:compute/0` —
  // matching on `compute` keeps the assertion stable if the formatter
  // changes between `module:function/arity` and `function/arity`.
  calltraceFunction: 'compute',
  // Erlang variables are capitalized; FinalResult is the canonical
  // end-state binding (== 94).
  variableName: 'FinalResult',
  langId: 'Erlang',
  // canonical_flow:main/0 prints `94` via io:format/2.
  terminalText: '94',
})
