import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-leo-fixture.sh.
// It records the Leo flow_test.leo program which:
//   - Performs field-element arithmetic operations
//   - Exercises the Leo interpreter tracer on the Aleo VM
defineLanguageSmokeTests({
  language: 'Leo',
  traceName: 'leo-flow-test',
  expectedFileName: 'flow_test.leo',
  calltraceFunction: 'compute',
  variableName: 'a',
  langId: 'Leo',
})
