import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-masm-fixture.sh.
// It records the Miden Assembly compute.masm program which:
//   - Performs stack-based arithmetic operations
//   - Exercises the Miden VM's MASM execution path
defineLanguageSmokeTests({
  language: 'MASM',
  traceName: 'masm-flow-test',
  expectedFileName: 'compute.masm',
  calltraceFunction: 'compute',
  variableName: 'local[0]',
  langId: 'MASM',
})
