import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-move-fixture.sh.
// It records the Move flow_test module's test_computation() function which:
//   - Performs arithmetic on u64 values
//   - Exercises the Move VM's execution and variable tracking
defineLanguageSmokeTests({
  language: 'Move',
  traceName: 'move-flow-test',
  expectedFileName: 'flow_test.move',
  calltraceFunction: 'test_computation',
  // The Move recorder surfaces real source variable names via the Move
  // VM debug-info metadata (`a`, `doubled`, `popped`, `stack_top`,
  // `sum_val`) rather than the synthetic `local_<index>` form the
  // trace consumer used to see when ``local_2`` was the canonical
  // pin.  Pinning against the source name keeps the smoke test honest
  // even if a future recorder change reshuffles slot indices.
  variableName: 'sum_val',
  langId: 'Move',
})
