import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-move-fixture.sh.
// It records the Move flow_test module's test_computation() function which:
//   - Performs arithmetic on u64 values
//   - Exercises the Move VM's execution and variable tracking
defineLanguageSmokeTests({
  language: 'Move',
  traceName: 'move-flow-test',
  expectedFileName: 'flow_test.move',
  calltraceFunction: 'test_computation',
  variableName: 'sum_val',
  langId: 'Move',
})
