import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-polkavm-fixture.sh.
// It builds a compute program blob programmatically via ProgramBlobBuilder
// (no RISC-V cross-compiler needed) and records the execution trace.
// Computes: (10 + 32) * 2 + 10 = 94 using registers A0, A1, S0, S1.
// Within the "main" function scope, A0-A5 are renamed to arg0-arg5.
defineLanguageSmokeTests({
  language: 'PolkaVM',
  traceName: 'polkavm-flow-test',
  expectedFileName: 'test_program.polkavm',
  calltraceFunction: 'main',
  variableName: 'arg0',
  langId: 'PolkaVM',
})
