/**
 * PolkaVM smoke tests for the CodeTracer VS Code extension.
 *
 * This is a custom smoke test suite because PolkaVM programs are binary blobs
 * (.polkavm) built programmatically via ProgramBlobBuilder — they have no
 * human-readable source files. VS Code cannot open binary blobs as text editor
 * tabs, so the generic defineLanguageSmokeTests (which asserts a tab opens)
 * is not suitable. Instead, we test purely at the DAP level.
 *
 * The fixture trace is generated by scripts/prepare-polkavm-fixture.sh.
 * It builds a compute program: (10 + 32) * 2 + 10 = 94 using registers
 * A0, A1, S0, S1. Within the "main" function scope, A0-A5 are renamed
 * to arg0-arg5 by the recorder's register name resolution.
 *
 * Source: codetracer-polkavm-recorder (ProgramBlobBuilder, no RISC-V compiler)
 */
import { expect } from '@wdio/globals'
import { DebugSession, ExtensionState } from '../../page-objects'
import {
  assertSessionStarts,
  assertThreadsExist,
  assertEventsPopulated,
  assertCalltraceContains,
  assertLocalsContainVariable,
} from '../../helpers/language-smoke-helpers'
import { captureFullDiagnostics, screenshot, writeDiag } from '../../helpers/diagnostics'
import { resolveTracePath, traceExists } from '../../helpers/trace-utils'

const TRACE_NAME = 'polkavm-flow-test'
const LANG_ID = 'PolkaVM'

// The "main" export in the PolkaVM blob should appear in the calltrace.
const CALLTRACE_FUNCTION = 'main'
// Within "main", A0 is renamed to arg0 by the recorder's debug info resolver.
const VARIABLE_NAME = 'arg0'

const session = new DebugSession()
const ext = new ExtensionState()

describe('CodeTracer Extension - PolkaVM Smoke Test', () => {
  let traceDir: string

  before(function () {
    traceDir = resolveTracePath(TRACE_NAME)
    if (!traceExists(TRACE_NAME)) {
      const message =
        `PolkaVM smoke tests: trace not found at ${traceDir}\n` +
        'Run scripts/prepare-polkavm-fixture.sh to generate it.'
      if (process.env.CI === 'true' || !!process.env.GITHUB_ACTIONS) {
        throw new Error(message)
      }
      console.warn(`SKIPPING ${message}`)
      this.skip()
    }
  })

  afterEach(async function () {
    const testName = this.currentTest?.title?.replace(/\s+/g, '-').substring(0, 50) ?? 'unknown'
    if (this.currentTest?.state === 'failed') {
      console.log(`[diag] Test failed: ${this.currentTest.title}`)
      await captureFullDiagnostics(`polkavm-FAIL-${testName}`)
    }
    await screenshot(`polkavm-${testName}`)
  })

  it('starts a debug session with the trace', async () => {
    await ext.ensureActivated()
    await assertSessionStarts(session, traceDir)

    const location = await session.currentLocation()
    console.log('[PolkaVM] Initial location:', JSON.stringify(location))
    writeDiag('polkavm-session-start.json', { location })
  })

  // PolkaVM programs are binary blobs (.polkavm) — VS Code cannot open them
  // as text editor tabs. Skip the editor tab assertion and test DAP directly.

  it('reports at least one DAP thread', async () => {
    await assertThreadsExist(session)
  })

  it('loads events from the trace', async () => {
    await assertEventsPopulated(session)
  })

  it(`finds ${CALLTRACE_FUNCTION} in the calltrace`, async () => {
    await assertCalltraceContains(session, CALLTRACE_FUNCTION)
  })

  it('can step-over via DAP', async () => {
    // Step-over and verify the DAP request succeeds. Since the program is a
    // binary blob without a text editor tab, we check the DAP response rather
    // than the editor cursor position.
    const result = await session.stepOverDap()
    expect(result.ok).toBe(true)
  })

  it(`finds ${VARIABLE_NAME} in local variables`, async () => {
    await assertLocalsContainVariable(session, VARIABLE_NAME, LANG_ID)
  })

  after(async () => {
    await captureFullDiagnostics('polkavm-final')
    try { await session.removeAllBreakpoints() } catch { /* ignore */ }
    try { await session.stop() } catch { /* ignore */ }
  })
})
