import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-polkavm-fixture.sh.
// It records the PolkaVM flow_test.pvm program which:
//   - Performs register-based arithmetic operations
//   - Exercises the PolkaVM execution path with step tracing
defineLanguageSmokeTests({
  language: 'PolkaVM',
  traceName: 'polkavm-flow-test',
  expectedFileName: 'flow_test.pvm',
  calltraceFunction: 'compute',
  variableName: 'A0',
  langId: 'PolkaVM',
})
