import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-solana-fixture.sh.
// It records a Solana BPF program's process_instruction() function which:
//   - Computes arithmetic on u64 values (add, multiply, add)
//   - Emits a log message with the result via solana_msg::msg!
defineLanguageSmokeTests({
  language: 'Solana',
  traceName: 'solana-flow-test',
  expectedFileName: 'solana_flow_test.rs',
  calltraceFunction: 'process_instruction',
  variableName: 'sum_val',
  langId: 'Solana',
  eventLogText: 'result',
  // TODO(FU-Writer-redux): drop once
  // codetracer-trace-format-nim's register_delta_column is
  // collapsed into the prior step's position.  The column-aware
  // writer currently emits each landing as a (line step, column
  // delta step) pair on the wire — line-granular step-over from
  // the call_entry lands on the empty line step and
  // ``variables_at(self.step_id)`` returns ``[]``.  One extra
  // ``next`` advances to the column-delta step that carries the
  // per-snapshot r0..r10 + named-locals emission.  Matches what
  // Ruby/Nim/Go set for the same class of issue.  See the
  // FU-Writer-redux follow-up against codetracer-trace-format-nim.
  extraStepsForLocals: 1,
})
