import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-solana-fixture.sh.
// It records a Solana BPF program's process_instruction() function which:
//   - Computes arithmetic on u64 values (add, multiply, add)
//   - Emits a log message with the result via solana_msg::msg!
defineLanguageSmokeTests({
  language: 'Solana',
  traceName: 'solana-flow-test',
  expectedFileName: 'solana_flow_test.rs',
  calltraceFunction: 'process_instruction',
  variableName: 'sum_val',
  langId: 'Solana',
  eventLogText: 'result',
})
