import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-solidity-fixture.sh.
// It records the FlowTest.sol contract's compute() function which:
//   - Calls the internal add() helper
//   - Writes to storedA and storedResult storage slots
//   - Emits a Computed event
defineLanguageSmokeTests({
  language: 'Solidity',
  traceName: 'solidity-flow-test',
  expectedFileName: 'FlowTest.sol',
  calltraceFunction: 'compute',
  variableName: 'result',
  langId: 'Solidity',
  // The Computed(uint256 result) event is emitted at the end of compute()
  eventLogText: 'Computed',
})
