/**
 * Solidity (EVM) smoke tests for the CodeTracer VS Code extension.
 *
 * This is a custom smoke test suite for Solidity/EVM rather than using the
 * generic defineLanguageSmokeTests helper. EVM traces have specific
 * characteristics that require tailored assertions:
 *
 *   - Function names in the calltrace use the synthetic "fn_at_<file>:<line>"
 *     format produced by the EVM recorder's source-map resolution, not
 *     high-level Solidity function names.
 *   - Local variables only appear after the debugger has stepped past the
 *     corresponding assignment opcodes. The initial trace position (step 0)
 *     and a single step-over may not be enough to reach a variable assignment.
 *   - Solidity events are recorded as raw EVM LOG operations
 *     (e.g. "LOG1: 0xabcd...") rather than decoded event names.
 *
 * The fixture trace is generated by scripts/prepare-solidity-fixture.sh.
 * It records the FlowTest.sol contract's compute() function which:
 *   - Assigns local variables a = 10, b = 20
 *   - Writes to storedA and storedResult storage slots (SSTORE)
 *   - Calls the internal add() helper
 *   - Emits a Computed event (LOG1 opcode)
 *
 * Source: codetracer-evm-recorder/contracts/FlowTest.sol
 */
import { expect } from '@wdio/globals'
import { DebugSession, EditorPane, ExtensionState } from '../../page-objects'
import {
  assertSessionStarts,
  assertEditorLoadsFile,
  assertThreadsExist,
  assertEventsPopulated,
  assertStepWorks,
} from '../../helpers/language-smoke-helpers'
import { captureFullDiagnostics, screenshot, writeDiag } from '../../helpers/diagnostics'
import { resolveTracePath, traceExists } from '../../helpers/trace-utils'

const TRACE_NAME = 'solidity-flow-test'
const EXPECTED_FILE = 'FlowTest.sol'
const LANG_ID = 'Solidity'

// The EVM recorder produces synthetic function names based on source-map
// resolution: "fn_at_<file_index>:<line>" (e.g. "fn_at_0:10").
// We check for the "fn_at_" prefix as a substring match.
const CALLTRACE_FUNCTION = 'fn_at_'

// The EVM recorder emits Solidity events as raw LOG operations.
// The Computed(uint256) event is a LOG1 containing the event signature topic.
const EVENT_LOG_TEXT = 'LOG1'

// Local variable assigned on line 11 of FlowTest.sol: `uint256 a = 10;`
// The EVM recorder emits source-level locals (not storage variables) in
// the DAP locals response. We look for `a` because it is the first
// variable assigned in compute().
const LOCAL_VAR_NAME = 'a'

// Maximum step-overs to try before giving up on finding the variable.
// Local variables appear once the debugger reaches the corresponding
// assignment. We step iteratively and check locals at each step.
const MAX_STEPS_FOR_LOCALS = 15

const session = new DebugSession()
const editor = new EditorPane()
const ext = new ExtensionState()

describe('CodeTracer Extension - Solidity Smoke Test', () => {
  let traceDir: string

  before(function () {
    traceDir = resolveTracePath(TRACE_NAME)
    if (!traceExists(TRACE_NAME)) {
      const message =
        `Solidity smoke tests: trace not found at ${traceDir}. ` +
        'Run scripts/prepare-solidity-fixture.sh to generate it.'
      console.warn(`SKIPPING: ${message}`)
      this.skip()
    }
  })

  afterEach(async function () {
    const testName = this.currentTest?.title?.replace(/[^a-zA-Z0-9_-]+/g, '-').substring(0, 50) ?? 'unknown'
    if (this.currentTest?.state === 'failed') {
      console.log(`[diag] Test failed: ${this.currentTest.title}`)
      await captureFullDiagnostics(`solidity-FAIL-${testName}`)
    }
    await screenshot(`solidity-${testName}`)
  })

  it('starts a debug session with the trace', async () => {
    await ext.ensureActivated()
    await assertSessionStarts(session, traceDir)

    const location = await session.currentLocation()
    console.log('[Solidity] Initial location:', JSON.stringify(location))
    writeDiag('solidity-session-start.json', { location })
  })

  it(`opens ${EXPECTED_FILE} in the editor`, async () => {
    await assertEditorLoadsFile(editor, EXPECTED_FILE)
  })

  it('reports at least one DAP thread', async () => {
    await assertThreadsExist(session)
  })

  it('loads events from the trace', async () => {
    await assertEventsPopulated(session)
  })

  it(`finds "${CALLTRACE_FUNCTION}" in the calltrace`, async () => {
    const result = await session.loadCalltrace({ depth: 50, height: 200 })
    if (result.ok && result.data) {
      const dataStr = JSON.stringify(result.data)
      writeDiag('calltrace.json', result.data)
      // The EVM recorder produces "fn_at_<file_index>:<line>" function names.
      expect(dataStr).toContain(CALLTRACE_FUNCTION)
    } else {
      console.warn('Calltrace did not return inline data:', result.error)
      expect(result.ok).toBe(true)
    }
  })

  it('can step-over and remain in the trace', async () => {
    await assertStepWorks(session)
  })

  it(`finds ${LOCAL_VAR_NAME} in local variables after stepping`, async () => {
    // Storage variables are carried forward but may not appear until the step
    // where the SSTORE fires. We step iteratively and check locals at each
    // step until we find the target variable or exhaust the budget.
    let found = false
    let lastLocals: any = null

    for (let i = 0; i < MAX_STEPS_FOR_LOCALS; i++) {
      await session.stepOver(500)

      const result = await session.loadLocals({ lang: LANG_ID, countBudget: 100, depthLimit: 3 })
      if (result.ok && result.data) {
        lastLocals = result.data
        const dataStr = JSON.stringify(result.data)
        if (dataStr.includes(LOCAL_VAR_NAME)) {
          console.log(`[Solidity] Found ${LOCAL_VAR_NAME} at step ${i + 1}`)
          writeDiag('locals.json', result.data)
          found = true
          break
        }
        // Log non-empty locals for diagnostics
        if (result.data.locals?.length > 0) {
          console.log(`[Solidity] Step ${i + 1}: ${result.data.locals.length} locals, ` +
            `names: ${result.data.locals.map((l: any) => l.name ?? l.variable_name).join(', ')}`)
        }
      }
    }

    if (!found) {
      writeDiag('locals-last.json', lastLocals)
    }
    expect(found).toBe(true)
  })

  it(`event log contains ${EVENT_LOG_TEXT}`, async () => {
    const result = await session.loadEvents()
    if (result.ok && result.data) {
      const dataStr = JSON.stringify(result.data)
      writeDiag('events.json', result.data)
      expect(dataStr).toContain(EVENT_LOG_TEXT)
    } else {
      console.warn('Events did not return inline data:', result.error)
      expect(result.ok).toBe(true)
    }
  })

  after(async () => {
    await captureFullDiagnostics('solidity-final')
    try { await session.removeAllBreakpoints() } catch { /* ignore */ }
    try { await session.stop() } catch { /* ignore */ }
  })
})
