import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-sway-fixture.sh.
// It builds a FuelVM bytecode program using fuel-asm (no forc compiler
// needed) and records the execution trace via the export_fixture test.
// Computes: r16=10, r17=32, r18=42, r19=84, r20=94 with log and return.
defineLanguageSmokeTests({
  language: 'Sway',
  traceName: 'sway-flow-test',
  expectedFileName: 'flow_test.sw',
  calltraceFunction: '<toplevel>',
  variableName: 'r18',
  langId: 'Sway',
})
