import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-sway-fixture.sh.
// It records the Sway flow_test contract's main() function which:
//   - Performs arithmetic on u64 values
//   - Exercises the Fuel VM's Sway execution path
defineLanguageSmokeTests({
  language: 'Sway',
  traceName: 'sway-flow-test',
  expectedFileName: 'main.sw',
  calltraceFunction: 'main',
  variableName: 'sum_val',
  langId: 'Sway',
})
