import { defineLanguageSmokeTests } from '../../helpers/language-smoke-helpers'

// The fixture trace is generated by scripts/prepare-tolk-fixture.sh.
// It records the Tolk flow_test.tolk program which:
//   - Performs stack-based TVM operations
//   - Exercises the Tolk/TON VM tracer
defineLanguageSmokeTests({
  language: 'Tolk',
  traceName: 'tolk-flow-test',
  expectedFileName: 'flow_test.tolk',
  calltraceFunction: 'compute',
  variableName: 'a',
  langId: 'Tolk',
  // main() only has `return compute()`, so step-over from depth 0 would
  // skip the entire compute() body. Use step-in to enter compute().
  useStepIn: true,
})
