name: Setup Nix Environment
description: Common steps for setting up the Nix environment

inputs:
  trusted-public-keys:
    description: Trusted public keys
    required: false
    default: ""
  substituters:
    description: Substituters
    required: false
    default: ""
  gh-token:
    description: GitHub token for accessing private repos
    required: true

runs:
  using: "composite"
  steps:
    - uses: metacraft-labs/metacraft-github-actions/setup-nix@main
      with:
        gh-token: ${{inputs.gh-token}}
        substituters: ${{inputs.substituters}}
        trusted-public-keys: ${{inputs.trusted-public-keys}}
