/**
 * Deep Aiken (Cardano) trace tests for the CodeTracer VS Code extension.
 *
 * Extends the smoke test coverage with:
 *   - Variable VALUE assertions (not just name existence)
 *   - Multi-step navigation with line change verification
 *   - Breakpoint placement and continue-to-breakpoint
 *   - Step-in / step-out navigation
 *   - Calltrace function verification
 *
 * Aiken compiles to UPLC (Untyped Plutus Lambda Calculus) which runs on the
 * CEK machine. The recorder traces CEK machine operations and maps them back
 * to Aiken source locations. Variables like `a` and `b` are bound in the
 * compute validator and evaluated through the CEK reduction steps.
 *
 * The fixture trace is generated by scripts/prepare-aiken-fixture.sh and
 * records the flow_test.ak program which implements a compute validator
 * performing arithmetic on bound variables.
 *
 * Source: codetracer-aiken-recorder/test-programs/aiken/flow_test.ak
 */
import { browser, expect } from '@wdio/globals'
import { DebugSession, EditorPane, ExtensionState } from '../../page-objects'
import { captureFullDiagnostics, screenshot, writeDiag } from '../../helpers/diagnostics'
import { resolveTracePath, traceExists } from '../../helpers/trace-utils'

const TRACE_NAME = 'aiken-flow-test'

// ---- Known trace data (flow_test.ak compute validator) ----
// The compute validator binds variables `a` and `b`, computes a `result`,
// and returns it. Under the hood, Aiken compiles to UPLC which is evaluated
// by the CEK machine — each variable binding corresponds to a CEK environment
// entry that the recorder captures as a local.
const KNOWN_FUNCTIONS = ['compute']
const KNOWN_VARIABLES = ['a', 'b']

// Maximum step-ins to find a variable with a value when iterating.
const MAX_STEPS_FOR_LOCALS = 12

const session = new DebugSession()
const editor = new EditorPane()
const ext = new ExtensionState()

describe('CodeTracer Extension - Aiken (Cardano) Deep Test', () => {
  let traceDir: string

  before(function () {
    traceDir = resolveTracePath(TRACE_NAME)
    if (!traceExists(TRACE_NAME)) {
      const message =
        `Aiken deep tests: trace not found at ${traceDir}\n` +
        'Run scripts/prepare-aiken-fixture.sh to generate it.'
      console.warn(`SKIPPING ${message}`)
      this.skip()
    }
  })

  afterEach(async function () {
    const testName = this.currentTest?.title?.replace(/[^a-zA-Z0-9_-]+/g, '-').substring(0, 50) ?? 'unknown'
    if (this.currentTest?.state === 'failed') {
      console.log(`[diag] Test failed: ${this.currentTest.title}`)
      await captureFullDiagnostics(`aiken-deep-FAIL-${testName}`)
    }
    await screenshot(`aiken-deep-${testName}`)
  })

  // ==================================================================
  // Session lifecycle
  // ==================================================================

  it('starts a debug session with the Aiken trace', async () => {
    await ext.ensureActivated()
    const started = await session.start(traceDir)
    expect(started).toBe(true)

    const active = await session.isActive()
    expect(active).toBe(true)

    const location = await session.currentLocation()
    console.log('[Aiken] Initial location:', JSON.stringify(location))
    writeDiag('aiken-deep-session-start.json', { started, active, location })
  })

  // ==================================================================
  // Editor: verify flow_test.ak opens
  // ==================================================================

  it('opens flow_test.ak in the editor', async () => {
    const hasTab = await editor.hasOpenTab('flow_test.ak')
    if (!hasTab) {
      await browser.waitUntil(
        async () => editor.hasOpenTab('flow_test.ak'),
        { timeout: 15000, timeoutMsg: 'flow_test.ak tab did not open within 15s' },
      )
    }

    // Activate the tab so subsequent checks work against it.
    await browser.executeWorkbench(async (vscode) => {
      for (const group of vscode.window.tabGroups.all) {
        for (const tab of group.tabs) {
          const input = tab.input as any
          if (input?.uri?.fsPath?.endsWith('flow_test.ak')) {
            await vscode.window.showTextDocument(input.uri)
            return
          }
        }
      }
    })
    await browser.pause(1000)

    const state = await editor.state()
    expect(state).not.toBeNull()
    expect(state!.fileName).toContain('flow_test.ak')
    writeDiag('aiken-deep-editor-state.json', state)
  })

  // ==================================================================
  // DAP threads
  // ==================================================================

  it('reports at least one DAP thread', async () => {
    const result = await session.getThreads()
    expect(result.ok).toBe(true)
    expect(result.data!.threads.length).toBeGreaterThanOrEqual(1)
    console.log('[Aiken] Threads:', JSON.stringify(result.data!.threads))
    writeDiag('aiken-deep-threads.json', result.data)
  })

  // ==================================================================
  // Calltrace: verify compute function appears
  // ==================================================================

  it('calltrace contains the compute function', async () => {
    const result = await session.loadCalltrace({ depth: 50, height: 200 })
    expect(result.ok).toBe(true)
    writeDiag('aiken-deep-calltrace.json', result.data)

    const dataStr = JSON.stringify(result.data)
    const foundFunctions = KNOWN_FUNCTIONS.filter(fn => dataStr.includes(fn))
    console.log('[Aiken] Calltrace functions found:', foundFunctions)
    expect(dataStr).toContain('compute')
  })

  // ==================================================================
  // Events: verify event log is populated
  // ==================================================================

  it('loads events from the trace', async () => {
    const result = await session.loadEvents()
    console.log('[Aiken] Events ok:', result.ok)

    expect(result.ok).toBe(true)

    if (result.data) {
      const dataStr = JSON.stringify(result.data)
      writeDiag('aiken-deep-events.json', result.data)
      // Events should have some content (more than an empty object)
      expect(dataStr.length).toBeGreaterThan(2)
    }
  })

  // ==================================================================
  // Locals: verify variable values (not just names)
  // ==================================================================

  it('finds variable with value after stepping into compute', async () => {
    // The entry function is merged into <toplevel> (depth 0). compute() is a
    // nested call at depth 1. We step forward iteratively with step-in to
    // enter compute() and reach the assignment steps where locals are populated.
    let found = false
    let lastLocals: any = null

    for (let i = 0; i < MAX_STEPS_FOR_LOCALS; i++) {
      await session.stepIn(500)

      const result = await session.loadLocals({ lang: 'Aiken', countBudget: 100, depthLimit: 3 })
      if (result.ok && result.data) {
        lastLocals = result.data
        const dataStr = JSON.stringify(result.data)
        if (dataStr.includes('a')) {
          if (result.data.locals && Array.isArray(result.data.locals)) {
            const withValues = result.data.locals.filter(
              (l: any) => l.value !== undefined && l.value !== null && String(l.value).length > 0,
            )
            if (withValues.length > 0) {
              console.log(`[Aiken] Found variable 'a' with value at step ${i + 1}`)
              writeDiag('aiken-deep-locals.json', result.data)
              for (const v of withValues.slice(0, 5)) {
                console.log(`  ${v.name ?? v.variable_name}: ${JSON.stringify(v.value).substring(0, 80)}`)
              }
              found = true
              break
            }
          }
        }
        if (result.data.locals?.length > 0) {
          console.log(`[Aiken] Step ${i + 1}: ${result.data.locals.length} locals, ` +
            `names: ${result.data.locals.map((l: any) => l.name ?? l.variable_name).join(', ')}`)
        }
      }
    }

    if (!found) {
      writeDiag('aiken-deep-locals-last.json', lastLocals)
    }
    expect(found).toBe(true)
  })

  // ==================================================================
  // Step navigation: multi-step and line change verification
  // ==================================================================

  it('performs multiple step-in operations and changes line', async () => {
    // Use step-in to advance through the trace regardless of call depth.
    const current = await session.currentLocation()
    console.log('[Aiken] Pre-step location:', JSON.stringify(current))

    const locations: Array<{ file: string; line: number }> = [current]

    for (let i = 0; i < 5; i++) {
      const loc = await session.stepIn(3000)
      locations.push(loc)
      expect(loc.file.length).toBeGreaterThan(0)
      expect(loc.line).toBeGreaterThan(0)
    }

    writeDiag('aiken-deep-multi-step.json', locations)
    console.log('[Aiken] Multi-step locations:', JSON.stringify(locations))

    // Verify we actually moved — lines should change across steps.
    const uniqueLines = new Set(locations.map(l => l.line))
    expect(uniqueLines.size).toBeGreaterThan(1)
  })

  it('step-in enters a callee and step-out returns', async () => {
    const before = await session.currentLocation()

    const inLoc = await session.stepIn(3000)
    expect(inLoc.file.length).toBeGreaterThan(0)
    expect(inLoc.line).toBeGreaterThan(0)
    writeDiag('aiken-deep-step-in.json', { before, inLoc })

    const outLoc = await session.stepOut(3000)
    expect(outLoc.file.length).toBeGreaterThan(0)
    expect(outLoc.line).toBeGreaterThan(0)
    writeDiag('aiken-deep-step-out.json', { inLoc, outLoc })
  })

  // ==================================================================
  // Breakpoints: set and continue
  // ==================================================================

  it('sets a breakpoint and continues to it', async () => {
    await session.removeAllBreakpoints()

    // Set breakpoint at line 5 — inside the compute validator body where
    // variable bindings (a, b) are evaluated by the CEK machine.
    const bpResult = await session.addBreakpoint(5)
    console.log('[Aiken] Breakpoint result:', JSON.stringify(bpResult))
    expect(bpResult.added).toBe(true)

    const breakpoints = await session.getBreakpoints()
    console.log('[Aiken] All breakpoints:', JSON.stringify(breakpoints))
    expect(breakpoints.some(bp => bp.line === 5)).toBe(true)

    const location = await session.continue(3000)
    console.log('[Aiken] Stopped at:', JSON.stringify(location))

    // After continue, we should be at a valid location
    expect(location.file.length).toBeGreaterThan(0)
    expect(location.line).toBeGreaterThan(0)

    writeDiag('aiken-deep-breakpoint.json', { bpResult, breakpoints, location })
  })

  // ==================================================================
  // Flow data
  // ==================================================================

  it('loads flow data for the current position', async () => {
    const result = await session.loadFlow(0)
    console.log('[Aiken] Flow ok:', result.ok)

    expect(result.ok).toBe(true)

    if (result.data) {
      writeDiag('aiken-deep-flow.json', result.data)
      console.log('[Aiken] Flow data keys:', Object.keys(result.data))
      const dataStr = JSON.stringify(result.data)
      expect(dataStr.length).toBeGreaterThan(2)
    }
  })

  // ==================================================================
  // Calltrace search
  // ==================================================================

  it('can search the calltrace for "compute"', async () => {
    const result = await session.searchCalltrace('compute')
    console.log('[Aiken] Search calltrace ok:', result.ok)
    expect(result.ok).toBe(true)

    if (result.data) {
      writeDiag('aiken-deep-search-compute.json', result.data)
    }
  })

  // ==================================================================
  // Cleanup
  // ==================================================================

  after(async () => {
    await captureFullDiagnostics('aiken-deep-final')
    try { await session.removeAllBreakpoints() } catch { /* ignore */ }
    try { await session.stop() } catch { /* ignore */ }
  })
})
