/**
 * Deep Cairo trace tests for the CodeTracer VS Code extension.
 *
 * Extends the smoke test coverage with:
 *   - Variable VALUE assertions (not just name existence)
 *   - Multi-step navigation with line change verification
 *   - Breakpoint placement and continue-to-breakpoint
 *   - Step-in / step-out navigation
 *   - Calltrace function verification
 *
 * The fixture trace is generated by scripts/prepare-cairo-fixture.sh and
 * records the flow_test.cairo program which performs felt-based arithmetic
 * in the Cairo VM. Cairo compiles to Sierra (intermediate representation)
 * with debug info mapping back to Cairo source.
 *
 * Source: codetracer-cairo-recorder/test-programs/cairo/flow_test.cairo
 */
import { browser, expect } from '@wdio/globals'
import { DebugSession, EditorPane, ExtensionState } from '../../page-objects'
import { captureFullDiagnostics, screenshot, writeDiag } from '../../helpers/diagnostics'
import { resolveTracePath, traceExists } from '../../helpers/trace-utils'

const TRACE_NAME = 'cairo-flow-test'

// ---- Known trace data (flow_test.cairo) ----
// The compute function performs felt-based arithmetic. Cairo uses felt252
// (field elements over a large prime) as its base numeric type. The Cairo VM
// executes Sierra IR with debug info mapping back to source locations.
const KNOWN_FUNCTIONS = ['compute']
const KNOWN_VARIABLE = 'a' // felt252 type

const session = new DebugSession()
const editor = new EditorPane()
const ext = new ExtensionState()

describe('CodeTracer Extension - Cairo Deep Test', () => {
  let traceDir: string

  before(function () {
    traceDir = resolveTracePath(TRACE_NAME)
    if (!traceExists(TRACE_NAME)) {
      const message =
        `Cairo deep tests: trace not found at ${traceDir}\n` +
        'Run scripts/prepare-cairo-fixture.sh to generate it.'
      if (process.env.CI === 'true' || !!process.env.GITHUB_ACTIONS) {
        throw new Error(message)
      }
      console.warn(`SKIPPING ${message}`)
      this.skip()
    }
  })

  afterEach(async function () {
    const testName = this.currentTest?.title?.replace(/\s+/g, '-').substring(0, 50) ?? 'unknown'
    if (this.currentTest?.state === 'failed') {
      console.log(`[diag] Test failed: ${this.currentTest.title}`)
      await captureFullDiagnostics(`cairo-deep-FAIL-${testName}`)
    }
    await screenshot(`cairo-deep-${testName}`)
  })

  // ==================================================================
  // Session lifecycle
  // ==================================================================

  it('starts a debug session with the Cairo trace', async () => {
    await ext.ensureActivated()
    const started = await session.start(traceDir)
    expect(started).toBe(true)

    const active = await session.isActive()
    expect(active).toBe(true)

    const location = await session.currentLocation()
    console.log('[Cairo] Initial location:', JSON.stringify(location))
    writeDiag('cairo-session-start.json', { started, active, location })
  })

  // ==================================================================
  // Editor: verify flow_test.cairo opens
  // ==================================================================

  it('opens flow_test.cairo in the editor', async () => {
    const hasTab = await editor.hasOpenTab('flow_test.cairo')
    if (!hasTab) {
      await browser.waitUntil(
        async () => editor.hasOpenTab('flow_test.cairo'),
        { timeout: 15000, timeoutMsg: 'flow_test.cairo tab did not open within 15s' },
      )
    }

    // Activate the tab so subsequent checks work against it.
    await browser.executeWorkbench(async (vscode) => {
      for (const group of vscode.window.tabGroups.all) {
        for (const tab of group.tabs) {
          const input = tab.input as any
          if (input?.uri?.fsPath?.endsWith('flow_test.cairo')) {
            await vscode.window.showTextDocument(input.uri)
            return
          }
        }
      }
    })
    await browser.pause(1000)

    const state = await editor.state()
    expect(state).not.toBeNull()
    expect(state!.fileName).toContain('flow_test.cairo')
    writeDiag('cairo-editor-state.json', state)
  })

  // ==================================================================
  // DAP threads
  // ==================================================================

  it('reports at least one DAP thread', async () => {
    const result = await session.getThreads()
    expect(result.ok).toBe(true)
    expect(result.data!.threads.length).toBeGreaterThanOrEqual(1)
    console.log('[Cairo] Threads:', JSON.stringify(result.data!.threads))
    writeDiag('cairo-threads.json', result.data)
  })

  // ==================================================================
  // Calltrace: verify compute function appears
  // ==================================================================

  it('calltrace contains the compute function', async () => {
    const result = await session.loadCalltrace({ depth: 50, height: 200 })
    expect(result.ok).toBe(true)
    writeDiag('cairo-calltrace.json', result.data)

    const dataStr = JSON.stringify(result.data)
    const foundFunctions = KNOWN_FUNCTIONS.filter(fn => dataStr.includes(fn))
    console.log('[Cairo] Calltrace functions found:', foundFunctions)
    expect(dataStr).toContain('compute')
  })

  // ==================================================================
  // Events: verify event log is populated
  // ==================================================================

  it('loads events from the trace', async () => {
    const result = await session.loadEvents()
    console.log('[Cairo] Events ok:', result.ok)

    expect(result.ok).toBe(true)

    if (result.data) {
      const dataStr = JSON.stringify(result.data)
      writeDiag('cairo-events.json', result.data)
      // Events should have some content (more than an empty object)
      expect(dataStr.length).toBeGreaterThan(2)
    }
  })

  // ==================================================================
  // Locals: verify variable values (not just names)
  // ==================================================================

  it('loads locals with variable values including a (felt252)', async () => {
    // The initial position is at main() which only calls compute(). Step into
    // compute() and advance past the variable assignments so locals are populated.
    const stepInLoc = await session.stepIn(3000)
    console.log('[Cairo] Stepped into:', JSON.stringify(stepInLoc))
    // Step over a few lines inside compute() to reach variable assignments
    for (let i = 0; i < 3; i++) {
      const loc = await session.stepOver(2000)
      console.log(`[Cairo] Step ${i + 1}:`, JSON.stringify(loc))
    }

    const result = await session.loadLocals({ lang: 'Cairo', countBudget: 100, depthLimit: 3 })
    expect(result.ok).toBe(true)
    writeDiag('cairo-deep-locals.json', result.data)

    if (result.data) {
      const dataStr = JSON.stringify(result.data)
      // Verify the known variable name is present (felt252 is the base numeric type in Cairo)
      expect(dataStr).toContain(KNOWN_VARIABLE)

      // Verify at least one variable has a non-empty value
      if (result.data.locals && Array.isArray(result.data.locals)) {
        console.log('[Cairo] Total locals:', result.data.locals.length)

        const withValues = result.data.locals.filter(
          (l: any) => l.value !== undefined && l.value !== null && String(l.value).length > 0,
        )
        console.log(`[Cairo] Locals with values: ${withValues.length}/${result.data.locals.length}`)
        expect(withValues.length).toBeGreaterThan(0)

        // Log first few for diagnostics
        for (const v of withValues.slice(0, 5)) {
          console.log(`  ${v.name ?? v.variable_name}: ${JSON.stringify(v.value).substring(0, 80)}`)
        }
      }
    }
  })

  // ==================================================================
  // Step navigation: multi-step and line change verification
  // ==================================================================

  it('performs multiple step-over operations and changes line', async () => {
    // After the locals test, we should already be inside compute().
    // Record current position to include in the set of visited lines.
    const current = await session.currentLocation()
    console.log('[Cairo] Pre-step location:', JSON.stringify(current))

    const locations: Array<{ file: string; line: number }> = [current]

    for (let i = 0; i < 5; i++) {
      const loc = await session.stepOver(3000)
      locations.push(loc)
      // Each step should land in a source file with a valid line
      expect(loc.file.length).toBeGreaterThan(0)
      expect(loc.line).toBeGreaterThan(0)
    }

    writeDiag('cairo-deep-multi-step.json', locations)
    console.log('[Cairo] Multi-step locations:', JSON.stringify(locations))

    // Verify we actually moved — not all locations should be the same line.
    // Inside compute(), lines 2-7 have variable assignments, so step-overs
    // should visit different lines.
    const uniqueLines = new Set(locations.map(l => l.line))
    expect(uniqueLines.size).toBeGreaterThan(1)
  })

  it('step-in enters a callee and step-out returns', async () => {
    const before = await session.currentLocation()

    const inLoc = await session.stepIn(3000)
    expect(inLoc.file.length).toBeGreaterThan(0)
    expect(inLoc.line).toBeGreaterThan(0)
    writeDiag('cairo-deep-step-in.json', { before, inLoc })

    const outLoc = await session.stepOut(3000)
    expect(outLoc.file.length).toBeGreaterThan(0)
    expect(outLoc.line).toBeGreaterThan(0)
    writeDiag('cairo-deep-step-out.json', { inLoc, outLoc })
  })

  // ==================================================================
  // Breakpoints: set and continue
  // ==================================================================

  it('sets a breakpoint and continues to it', async () => {
    await session.removeAllBreakpoints()

    // Set breakpoint at an early line in flow_test.cairo. Cairo programs
    // typically have function definitions in the first few lines.
    const bpResult = await session.addBreakpoint(5)
    console.log('[Cairo] Breakpoint result:', JSON.stringify(bpResult))
    expect(bpResult.added).toBe(true)

    const breakpoints = await session.getBreakpoints()
    console.log('[Cairo] All breakpoints:', JSON.stringify(breakpoints))
    expect(breakpoints.some(bp => bp.line === 5)).toBe(true)

    const location = await session.continue(3000)
    console.log('[Cairo] Stopped at:', JSON.stringify(location))

    // After continue, we should be at a valid location
    expect(location.file.length).toBeGreaterThan(0)
    expect(location.line).toBeGreaterThan(0)

    writeDiag('cairo-deep-breakpoint.json', { bpResult, breakpoints, location })
  })

  // ==================================================================
  // Flow data
  // ==================================================================

  it('loads flow data for the current position', async () => {
    const result = await session.loadFlow(0)
    console.log('[Cairo] Flow ok:', result.ok)

    expect(result.ok).toBe(true)

    if (result.data) {
      writeDiag('cairo-deep-flow.json', result.data)
      console.log('[Cairo] Flow data keys:', Object.keys(result.data))
      const dataStr = JSON.stringify(result.data)
      expect(dataStr.length).toBeGreaterThan(2)
    }
  })

  // ==================================================================
  // Calltrace search
  // ==================================================================

  it('can search the calltrace for "compute"', async () => {
    const result = await session.searchCalltrace('compute')
    console.log('[Cairo] Search calltrace ok:', result.ok)
    expect(result.ok).toBe(true)

    if (result.data) {
      writeDiag('cairo-deep-search-compute.json', result.data)
    }
  })

  // ==================================================================
  // Cleanup
  // ==================================================================

  after(async () => {
    await captureFullDiagnostics('cairo-deep-final')
    try { await session.removeAllBreakpoints() } catch { /* ignore */ }
    try { await session.stop() } catch { /* ignore */ }
  })
})
