/**
 * Deep PolkaVM trace tests for the CodeTracer VS Code extension.
 *
 * Extends the smoke test coverage with:
 *   - Variable VALUE assertions (not just name existence)
 *   - Multi-step navigation via DAP
 *   - Calltrace function verification
 *   - Calltrace search
 *
 * PolkaVM is a register-based virtual machine for the Polkadot ecosystem.
 * Unlike stack-based VMs (e.g. Miden), PolkaVM uses registers (A0, A1, etc.)
 * for computation. The recorder traces execution at the register level with
 * step tracing.
 *
 * The fixture trace is generated by scripts/prepare-polkavm-fixture.sh and
 * records a compute program built programmatically via ProgramBlobBuilder
 * (no RISC-V cross-compiler needed). The program computes:
 *   (10 + 32) * 2 + 10 = 94 using registers A0, A1, S0, S1.
 *
 * IMPORTANT: PolkaVM programs are binary blobs (.polkavm) without
 * human-readable source files. VS Code cannot open binary blobs as text
 * editor tabs, so all assertions are DAP-level (no editor tab checks).
 * Within the "main" function scope, A0-A5 are renamed to arg0-arg5.
 *
 * Source: codetracer-polkavm-recorder (ProgramBlobBuilder)
 */
import { expect } from '@wdio/globals'
import { DebugSession, ExtensionState } from '../../page-objects'
import { captureFullDiagnostics, screenshot, writeDiag } from '../../helpers/diagnostics'
import { resolveTracePath, traceExists } from '../../helpers/trace-utils'

const TRACE_NAME = 'polkavm-flow-test'

// ---- Known trace data (test_program.polkavm) ----
// The program has a single "main" export. Within the function scope,
// A0-A5 are renamed to arg0-arg5 by the recorder's register name resolver.
const KNOWN_FUNCTIONS = ['main']
const KNOWN_VARIABLE = 'arg0'

const session = new DebugSession()
const ext = new ExtensionState()

describe('CodeTracer Extension - PolkaVM Deep Test', () => {
  let traceDir: string

  before(function () {
    traceDir = resolveTracePath(TRACE_NAME)
    if (!traceExists(TRACE_NAME)) {
      const message =
        `PolkaVM deep tests: trace not found at ${traceDir}\n` +
        'Run scripts/prepare-polkavm-fixture.sh to generate it.'
      if (process.env.CI === 'true' || !!process.env.GITHUB_ACTIONS) {
        throw new Error(message)
      }
      console.warn(`SKIPPING ${message}`)
      this.skip()
    }
  })

  afterEach(async function () {
    const testName = this.currentTest?.title?.replace(/\s+/g, '-').substring(0, 50) ?? 'unknown'
    if (this.currentTest?.state === 'failed') {
      console.log(`[diag] Test failed: ${this.currentTest.title}`)
      await captureFullDiagnostics(`polkavm-deep-FAIL-${testName}`)
    }
    await screenshot(`polkavm-deep-${testName}`)
  })

  // ==================================================================
  // Session lifecycle
  // ==================================================================

  it('starts a debug session with the PolkaVM trace', async () => {
    await ext.ensureActivated()
    const started = await session.start(traceDir)
    expect(started).toBe(true)

    const active = await session.isActive()
    expect(active).toBe(true)

    // PolkaVM programs are binary blobs — no editor tab opens, so we must
    // explicitly wait for the backend to finish initialization. Other languages
    // use the editor tab wait (15s) as a natural barrier.
    await session.waitForBackendReady()

    const location = await session.currentLocation()
    console.log('[PolkaVM] Initial location:', JSON.stringify(location))
    writeDiag('polkavm-session-start.json', { started, active, location })
  })

  // ==================================================================
  // DAP threads
  // ==================================================================

  it('reports at least one DAP thread', async () => {
    const result = await session.getThreads()
    expect(result.ok).toBe(true)
    expect(result.data!.threads.length).toBeGreaterThanOrEqual(1)
    console.log('[PolkaVM] Threads:', JSON.stringify(result.data!.threads))
    writeDiag('polkavm-threads.json', result.data)
  })

  // ==================================================================
  // Calltrace: verify main function appears
  // ==================================================================

  it('calltrace contains the main function', async () => {
    const result = await session.loadCalltrace({ depth: 50, height: 200 })
    expect(result.ok).toBe(true)
    writeDiag('polkavm-calltrace.json', result.data)

    const dataStr = JSON.stringify(result.data)
    const foundFunctions = KNOWN_FUNCTIONS.filter(fn => dataStr.includes(fn))
    console.log('[PolkaVM] Calltrace functions found:', foundFunctions)
    expect(dataStr).toContain('main')
  })

  // ==================================================================
  // Events: verify event log is populated
  // ==================================================================

  it('loads events from the trace', async () => {
    const result = await session.loadEvents()
    console.log('[PolkaVM] Events ok:', result.ok)

    expect(result.ok).toBe(true)

    if (result.data) {
      const dataStr = JSON.stringify(result.data)
      writeDiag('polkavm-events.json', result.data)
      // Events should have some content (more than an empty object)
      expect(dataStr.length).toBeGreaterThan(2)
    }
  })

  // ==================================================================
  // Locals: verify register values (not just names)
  // ==================================================================

  it('loads locals with register values including arg0', async () => {
    const result = await session.loadLocals({ lang: 'PolkaVM', countBudget: 100, depthLimit: 3 })
    expect(result.ok).toBe(true)
    writeDiag('polkavm-deep-locals.json', result.data)

    if (result.data) {
      const dataStr = JSON.stringify(result.data)
      // Verify the known register name is present (A0 renamed to arg0 in scope)
      expect(dataStr).toContain(KNOWN_VARIABLE)

      // Verify at least one register has a non-empty value
      if (result.data.locals && Array.isArray(result.data.locals)) {
        console.log('[PolkaVM] Total locals:', result.data.locals.length)

        const withValues = result.data.locals.filter(
          (l: any) => l.value !== undefined && l.value !== null && String(l.value).length > 0,
        )
        console.log(`[PolkaVM] Locals with values: ${withValues.length}/${result.data.locals.length}`)
        expect(withValues.length).toBeGreaterThan(0)

        // Log first few for diagnostics
        for (const v of withValues.slice(0, 5)) {
          console.log(`  ${v.name ?? v.variable_name}: ${JSON.stringify(v.value).substring(0, 80)}`)
        }
      }
    }
  })

  // ==================================================================
  // Step navigation via DAP (no editor tab for binary blobs)
  // ==================================================================

  it('performs multiple step-over operations via DAP', async () => {
    const results: Array<{ ok: boolean }> = []

    for (let i = 0; i < 5; i++) {
      const result = await session.stepOverDap(1500)
      results.push({ ok: result.ok })
      expect(result.ok).toBe(true)
    }

    writeDiag('polkavm-deep-multi-step.json', results)
    console.log('[PolkaVM] Multi-step results:', JSON.stringify(results))
  })

  // ==================================================================
  // Flow data
  // ==================================================================

  it('loads flow data for the current position', async () => {
    const result = await session.loadFlow(0)
    console.log('[PolkaVM] Flow ok:', result.ok)

    expect(result.ok).toBe(true)

    if (result.data) {
      writeDiag('polkavm-deep-flow.json', result.data)
      console.log('[PolkaVM] Flow data keys:', Object.keys(result.data))
      const dataStr = JSON.stringify(result.data)
      expect(dataStr.length).toBeGreaterThan(2)
    }
  })

  // ==================================================================
  // Calltrace search
  // ==================================================================

  it('can search the calltrace for "main"', async () => {
    const result = await session.searchCalltrace('main')
    console.log('[PolkaVM] Search calltrace ok:', result.ok)
    expect(result.ok).toBe(true)

    if (result.data) {
      writeDiag('polkavm-deep-search-main.json', result.data)
    }
  })

  // ==================================================================
  // Cleanup
  // ==================================================================

  after(async () => {
    await captureFullDiagnostics('polkavm-deep-final')
    try { await session.removeAllBreakpoints() } catch { /* ignore */ }
    try { await session.stop() } catch { /* ignore */ }
  })
})
