/**
 * Deep Solana trace tests for the CodeTracer VS Code extension.
 *
 * Extends the smoke test coverage with:
 *   - Variable VALUE assertions (not just name existence)
 *   - Multi-step navigation with line change verification
 *   - Breakpoint placement and continue-to-breakpoint
 *   - Step-in / step-out navigation
 *   - Calltrace function verification
 *   - Event log content verification (Solana msg! output)
 *
 * The fixture trace is generated by scripts/prepare-solana-fixture.sh and
 * records a Solana BPF program's process_instruction() function which
 * computes arithmetic on u64 values and emits a log message via msg!.
 *
 * Source: codetracer-solana-recorder/test-programs/src/lib.rs
 */
import { browser, expect } from '@wdio/globals'
import { DebugSession, EditorPane, ExtensionState } from '../../page-objects'
import { captureFullDiagnostics, screenshot, writeDiag } from '../../helpers/diagnostics'
import { resolveTracePath, traceExists } from '../../helpers/trace-utils'

const TRACE_NAME = 'solana-flow-test'

// ---- Known trace data (solana_flow_test.rs process_instruction()) ----
// The process_instruction function computes:
//   sum_val = a + b
//   doubled = sum_val * 2
//   final_result = doubled + 1
// Then emits a log message with the result via solana_msg::msg!.
const KNOWN_FUNCTIONS = ['process_instruction']
const KNOWN_VARIABLES = ['sum_val', 'doubled', 'final_result']
const KNOWN_EVENT_TEXT = 'result'

const session = new DebugSession()
const editor = new EditorPane()
const ext = new ExtensionState()

describe('CodeTracer Extension - Solana Deep Test', () => {
  let traceDir: string

  before(function () {
    traceDir = resolveTracePath(TRACE_NAME)
    if (!traceExists(TRACE_NAME)) {
      const message =
        `Solana deep tests: trace not found at ${traceDir}\n` +
        'Run scripts/prepare-solana-fixture.sh to generate it.'
      console.warn(`SKIPPING ${message}`)
      this.skip()
    }
  })

  afterEach(async function () {
    const testName = this.currentTest?.title?.replace(/\s+/g, '-').substring(0, 50) ?? 'unknown'
    if (this.currentTest?.state === 'failed') {
      console.log(`[diag] Test failed: ${this.currentTest.title}`)
      await captureFullDiagnostics(`solana-deep-FAIL-${testName}`)
    }
    await screenshot(`solana-deep-${testName}`)
  })

  // ==================================================================
  // Session lifecycle
  // ==================================================================

  it('starts a debug session with the Solana trace', async () => {
    await ext.ensureActivated()
    const started = await session.start(traceDir)
    expect(started).toBe(true)

    const active = await session.isActive()
    expect(active).toBe(true)

    const location = await session.currentLocation()
    console.log('[Solana] Initial location:', JSON.stringify(location))
    writeDiag('solana-session-start.json', { started, active, location })
  })

  // ==================================================================
  // Editor: verify solana_flow_test.rs opens
  // ==================================================================

  it('opens solana_flow_test.rs in the editor', async () => {
    const hasTab = await editor.hasOpenTab('solana_flow_test.rs')
    if (!hasTab) {
      await browser.waitUntil(
        async () => editor.hasOpenTab('solana_flow_test.rs'),
        { timeout: 15000, timeoutMsg: 'solana_flow_test.rs tab did not open within 15s' },
      )
    }

    await browser.executeWorkbench(async (vscode) => {
      for (const group of vscode.window.tabGroups.all) {
        for (const tab of group.tabs) {
          const input = tab.input as any
          if (input?.uri?.fsPath?.endsWith('solana_flow_test.rs')) {
            await vscode.window.showTextDocument(input.uri)
            return
          }
        }
      }
    })
    await browser.pause(1000)

    const state = await editor.state()
    expect(state).not.toBeNull()
    expect(state!.fileName).toContain('solana_flow_test.rs')
    writeDiag('solana-editor-state.json', state)
  })

  // ==================================================================
  // DAP threads
  // ==================================================================

  it('reports at least one DAP thread', async () => {
    const result = await session.getThreads()
    expect(result.ok).toBe(true)
    expect(result.data!.threads.length).toBeGreaterThanOrEqual(1)
    console.log('[Solana] Threads:', JSON.stringify(result.data!.threads))
    writeDiag('solana-threads.json', result.data)
  })

  // ==================================================================
  // Calltrace: verify process_instruction function appears
  // ==================================================================

  it('calltrace contains the process_instruction function', async () => {
    const result = await session.loadCalltrace({ depth: 50, height: 200 })
    expect(result.ok).toBe(true)
    writeDiag('solana-calltrace.json', result.data)

    const dataStr = JSON.stringify(result.data)
    const foundFunctions = KNOWN_FUNCTIONS.filter(fn => dataStr.includes(fn))
    console.log('[Solana] Calltrace functions found:', foundFunctions)
    expect(dataStr).toContain('process_instruction')
  })

  // ==================================================================
  // Events: verify event log contains "result" text from msg! output
  // ==================================================================

  it('event log contains Solana msg! output with "result"', async () => {
    const result = await session.loadEvents()
    console.log('[Solana] Events ok:', result.ok)

    expect(result.ok).toBe(true)

    if (result.data) {
      const dataStr = JSON.stringify(result.data)
      writeDiag('solana-events.json', result.data)

      // The Solana test program emits a msg! with "result" in the text
      expect(dataStr).toContain(KNOWN_EVENT_TEXT)
      console.log(`[Solana] Event log contains "${KNOWN_EVENT_TEXT}": true`)
    }
  })

  // ==================================================================
  // Locals: verify variable values (not just names)
  // ==================================================================

  it('loads locals with variable values including sum_val', async () => {
    const result = await session.loadLocals({ lang: 'Solana', countBudget: 100, depthLimit: 3 })
    expect(result.ok).toBe(true)
    writeDiag('solana-deep-locals.json', result.data)

    if (result.data) {
      const dataStr = JSON.stringify(result.data)

      // Verify known variable names are present
      const foundVars = KNOWN_VARIABLES.filter(v => dataStr.includes(v))
      console.log('[Solana] Found variables:', foundVars)

      // At least the primary variable (sum_val) should exist
      expect(dataStr).toContain('sum_val')

      // Verify at least one variable has a non-empty value
      if (result.data.locals && Array.isArray(result.data.locals)) {
        console.log('[Solana] Total locals:', result.data.locals.length)

        const withValues = result.data.locals.filter(
          (l: any) => l.value !== undefined && l.value !== null && String(l.value).length > 0,
        )
        console.log(`[Solana] Locals with values: ${withValues.length}/${result.data.locals.length}`)
        expect(withValues.length).toBeGreaterThan(0)

        for (const v of withValues.slice(0, 5)) {
          console.log(`  ${v.name ?? v.variable_name}: ${JSON.stringify(v.value).substring(0, 80)}`)
        }
      }
    }
  })

  // ==================================================================
  // Step navigation: multi-step and line change verification
  // ==================================================================

  it('performs multiple step-over operations and changes line', async () => {
    const locations: Array<{ file: string; line: number }> = []

    for (let i = 0; i < 5; i++) {
      const loc = await session.stepOver(3000)
      locations.push(loc)
      expect(loc.file.length).toBeGreaterThan(0)
      expect(loc.line).toBeGreaterThan(0)
    }

    writeDiag('solana-deep-multi-step.json', locations)
    console.log('[Solana] Multi-step locations:', JSON.stringify(locations))

    // Verify we actually moved through different lines
    const uniqueLines = new Set(locations.map(l => l.line))
    expect(uniqueLines.size).toBeGreaterThan(1)
  })

  it('step-in enters a callee and step-out returns', async () => {
    const before = await session.currentLocation()

    const inLoc = await session.stepIn(3000)
    expect(inLoc.file.length).toBeGreaterThan(0)
    expect(inLoc.line).toBeGreaterThan(0)
    writeDiag('solana-deep-step-in.json', { before, inLoc })

    const outLoc = await session.stepOut(3000)
    expect(outLoc.file.length).toBeGreaterThan(0)
    expect(outLoc.line).toBeGreaterThan(0)
    writeDiag('solana-deep-step-out.json', { inLoc, outLoc })
  })

  // ==================================================================
  // Breakpoints: set and continue
  // ==================================================================

  it('sets a breakpoint and continues to it', async () => {
    await session.removeAllBreakpoints()

    // Set breakpoint at line 10 — inside the process_instruction() function
    // body where arithmetic assignments occur.
    const bpResult = await session.addBreakpoint(10)
    console.log('[Solana] Breakpoint result:', JSON.stringify(bpResult))
    expect(bpResult.added).toBe(true)

    const breakpoints = await session.getBreakpoints()
    console.log('[Solana] All breakpoints:', JSON.stringify(breakpoints))
    expect(breakpoints.some(bp => bp.line === 10)).toBe(true)

    const location = await session.continue(3000)
    console.log('[Solana] Stopped at:', JSON.stringify(location))

    expect(location.file.length).toBeGreaterThan(0)
    expect(location.line).toBeGreaterThan(0)

    writeDiag('solana-deep-breakpoint.json', { bpResult, breakpoints, location })
  })

  // ==================================================================
  // Flow data
  // ==================================================================

  it('loads flow data for the current position', async () => {
    const result = await session.loadFlow(0)
    console.log('[Solana] Flow ok:', result.ok)

    expect(result.ok).toBe(true)

    if (result.data) {
      writeDiag('solana-deep-flow.json', result.data)
      console.log('[Solana] Flow data keys:', Object.keys(result.data))
      const dataStr = JSON.stringify(result.data)
      expect(dataStr.length).toBeGreaterThan(2)
    }
  })

  // ==================================================================
  // Calltrace search
  // ==================================================================

  it('can search the calltrace for "process_instruction"', async () => {
    const result = await session.searchCalltrace('process_instruction')
    console.log('[Solana] Search calltrace ok:', result.ok)
    expect(result.ok).toBe(true)

    if (result.data) {
      writeDiag('solana-deep-search-process_instruction.json', result.data)
    }
  })

  // ==================================================================
  // Cleanup
  // ==================================================================

  after(async () => {
    await captureFullDiagnostics('solana-deep-final')
    try { await session.removeAllBreakpoints() } catch { /* ignore */ }
    try { await session.stop() } catch { /* ignore */ }
  })
})
