/**
 * Deep Solidity (EVM) trace tests for the CodeTracer VS Code extension.
 *
 * Verifies EVM-specific debugging features using the FlowTest.sol fixture:
 *   - Storage/local variable inspection at the current EVM stop
 *   - Solidity LOG payload display for the Computed event
 *   - Internal function call visualization (compute → add)
 *   - Step navigation through Solidity source lines
 *   - Breakpoint placement at a specific contract line
 *
 * The fixture traces the FlowTest.compute() call which:
 *   1. Assigns uint256 a = 10, b = 20
 *   2. Writes storedA = a  (SSTORE opcode)
 *   3. Calls the internal add(a, b) helper
 *   4. Writes storedResult = result  (SSTORE opcode)
 *   5. Emits Computed(result)  (LOG1 opcode)
 *   6. Returns result (= 30)
 *
 * Source: codetracer-evm-recorder/contracts/FlowTest.sol
 * Fixture: generated by scripts/prepare-solidity-fixture.sh
 */
import { browser, expect } from '@wdio/globals'
import { DebugSession, EditorPane, ExtensionState } from '../../page-objects'
import { captureFullDiagnostics, screenshot, writeDiag } from '../../helpers/diagnostics'
import { resolveTracePath, traceExists } from '../../helpers/trace-utils'

const TRACE_NAME = 'solidity-flow-test'

// ---- Known trace data (FlowTest.sol compute() call) ----
// These values come from the contract source and EVM execution.
// See: codetracer-evm-recorder/contracts/FlowTest.sol
const KNOWN_FUNCTIONS = ['compute', 'add']
const KNOWN_STORAGE_VARS = ['storedA']
// The EVM recorder currently exposes Solidity events as raw LOG payloads.
const COMPUTED_EVENT_TOPIC_PREFIX = '0xaccb7b7f216abc04'
const COMPUTED_RESULT_HEX = '0x000000000000000000000000000000000000000000000000000000000000001e'
// At the current stop, DAP locals expose the storedA write and add(x, y) arguments.
const KNOWN_LOCALS = ['storedA', 'x', 'y']

const session = new DebugSession()
const editor = new EditorPane()
const ext = new ExtensionState()

function assertOkResult<T extends { ok: boolean; data?: unknown; error?: unknown }>(
  result: T,
  requestName: string,
): asserts result is T & { ok: true; data: NonNullable<T['data']> } {
  if (!result.ok) {
    throw new Error(`${requestName} request failed: ${result.error ?? 'unknown error'}`)
  }
  if (result.data === undefined || result.data === null) {
    throw new Error(`${requestName} request must return inline data`)
  }
}

describe('CodeTracer Extension - Solidity EVM Deep Test', () => {
  let traceDir: string

  before(function () {
    traceDir = resolveTracePath(TRACE_NAME)
    if (!traceExists(TRACE_NAME)) {
      const message =
        `Solidity deep tests: trace not found at ${traceDir}\n` +
        'Run scripts/prepare-solidity-fixture.sh to generate it.\n' +
        'Requires: solc, anvil, cargo, and codetracer-evm-recorder repo as a sibling.'
      throw new Error(message)
    }
  })

  afterEach(async function () {
    const testName = this.currentTest?.title?.replace(/[^a-zA-Z0-9_-]+/g, '-').substring(0, 50) ?? 'unknown'
    if (this.currentTest?.state === 'failed') {
      console.log(`[diag] Test failed: ${this.currentTest.title}`)
      await captureFullDiagnostics(`solidity-deep-FAIL-${testName}`)
    }
    await screenshot(`solidity-deep-${testName}`)
  })

  // ==================================================================
  // Session lifecycle
  // ==================================================================

  it('starts a debug session with the Solidity EVM trace', async () => {
    await ext.ensureActivated()
    const started = await session.start(traceDir)
    expect(started).toBe(true)

    const active = await session.isActive()
    expect(active).toBe(true)

    const location = await session.currentLocation()
    console.log('[Solidity] Initial location:', JSON.stringify(location))
    writeDiag('solidity-session-start.json', { started, active, location })
  })

  it('opens FlowTest.sol in the editor', async () => {
    // The debugger should open FlowTest.sol when the trace starts.
    const hasTab = await editor.hasOpenTab('FlowTest.sol')
    if (!hasTab) {
      await browser.waitUntil(
        async () => editor.hasOpenTab('FlowTest.sol'),
        { timeout: 15000, timeoutMsg: 'FlowTest.sol tab did not open within 15s' },
      )
    }

    // Bring FlowTest.sol into focus so subsequent editor assertions work.
    await browser.executeWorkbench(async (vscode) => {
      for (const group of vscode.window.tabGroups.all) {
        for (const tab of group.tabs) {
          const input = tab.input as any
          if (input?.uri?.fsPath?.endsWith('FlowTest.sol')) {
            await vscode.window.showTextDocument(input.uri)
            return
          }
        }
      }
    })
    await browser.pause(1000)

    const state = await editor.state()
    expect(state).not.toBeNull()
    expect(state!.fileName).toContain('FlowTest.sol')
    writeDiag('solidity-editor-state.json', state)
  })

  it('shows Solidity source with pragma and contract definitions', async () => {
    const source = await editor.getText()
    expect(source.length).toBeGreaterThan(0)

    // Verify the contract structure is present in source
    expect(source).toContain('pragma solidity')
    expect(source).toContain('contract FlowTest')
    expect(source).toContain('function compute')
    expect(source).toContain('function add')

    console.log('[Solidity] Source length:', source.length)
    writeDiag('solidity-source-content.txt', source.substring(0, 3000))
  })

  // ==================================================================
  // DAP threads
  // ==================================================================

  it('reports at least one DAP thread', async () => {
    const result = await session.getThreads()
    expect(result.ok).toBe(true)
    expect(result.data!.threads.length).toBeGreaterThanOrEqual(1)
    console.log('[Solidity] Threads:', JSON.stringify(result.data!.threads))
    writeDiag('solidity-threads.json', result.data)
  })

  // ==================================================================
  // Calltrace: cross-contract call visualization
  //   compute() → add()  (internal call, both in FlowTest.sol)
  // ==================================================================

  it('calltrace contains compute() and its internal add() callee', async () => {
    const result = await session.loadCalltrace({ depth: 50, height: 200 })
    console.log('[Solidity] Calltrace ok:', result.ok)

    assertOkResult(result, 'Calltrace')

    const dataStr = JSON.stringify(result.data)
    writeDiag('solidity-calltrace.json', result.data)

    const missingFunctions = KNOWN_FUNCTIONS.filter(fn => !dataStr.includes(fn))
    console.log('[Solidity] Missing calltrace functions:', missingFunctions)
    if (missingFunctions.length > 0) {
      throw new Error(`Calltrace must include ${KNOWN_FUNCTIONS.join(', ')}; missing: ${missingFunctions.join(', ')}`)
    }
    expect(missingFunctions).toEqual([])
  })

  // ==================================================================
  // Event log: Solidity LOG payload display
  //   The trace should contain the Computed(result) event emitted by
  //   the contract's `emit Computed(result)` statement (LOG1 opcode).
  // ==================================================================

  it('event log contains the Computed(uint256) LOG topic and result payload', async () => {
    const result = await session.loadEvents()
    console.log('[Solidity] Events ok:', result.ok)

    assertOkResult(result, 'Events')

    const dataStr = JSON.stringify(result.data)
    writeDiag('solidity-events.json', result.data)

    const missingPayloadParts = [COMPUTED_EVENT_TOPIC_PREFIX, COMPUTED_RESULT_HEX].filter(part => !dataStr.includes(part))
    console.log('[Solidity] Missing EVM payload parts:', missingPayloadParts)
    if (missingPayloadParts.length > 0) {
      throw new Error(`Event log must include Computed(uint256) raw LOG payload; missing: ${missingPayloadParts.join(', ')}`)
    }
    expect(missingPayloadParts).toEqual([])
  })

  // ==================================================================
  // Storage variable inspection
  //   EVM-specific: Solidity state variables map to storage slots.
  //   The current stop exposes storedA plus add(x, y) arguments. The lower-level
  //   Solidity DAP tests intentionally exclude `storedResult` as a local.
  // ==================================================================

  it('local variables include current EVM storage and add() arguments', async () => {
    const result = await session.loadLocals({ lang: 'Solidity', countBudget: 100, depthLimit: 3 })
    console.log('[Solidity] Locals ok:', result.ok)

    assertOkResult(result, 'Locals')

    const dataStr = JSON.stringify(result.data)
    writeDiag('solidity-locals.json', result.data)

    const missingLocals = KNOWN_LOCALS.filter(v => !dataStr.includes(v))
    const missingStorage = KNOWN_STORAGE_VARS.filter(v => !dataStr.includes(v))
    console.log('[Solidity] Missing locals:', missingLocals)
    console.log('[Solidity] Missing storage vars:', missingStorage)
    if (missingLocals.length > 0) {
      throw new Error(`Locals must include ${KNOWN_LOCALS.join(', ')}; missing: ${missingLocals.join(', ')}`)
    }
    if (missingStorage.length > 0) {
      throw new Error(`Storage vars must include ${KNOWN_STORAGE_VARS.join(', ')}; missing: ${missingStorage.join(', ')}`)
    }
    expect(missingLocals).toEqual([])
    expect(missingStorage).toEqual([])

    if (result.data.locals && Array.isArray(result.data.locals)) {
      console.log('[Solidity] Total locals:', result.data.locals.length)
      for (const local of result.data.locals.slice(0, 10)) {
        console.log(
          `  ${local.name ?? local.variable_name}: ` +
          JSON.stringify(local).substring(0, 120),
        )
      }

      const withValues = result.data.locals.filter(
        (l: any) => l.value !== undefined && l.value !== null && String(l.value).length > 0,
      )
      console.log(`[Solidity] Locals with values: ${withValues.length}/${result.data.locals.length}`)
      if (withValues.length === 0) {
        throw new Error('Solidity locals should include at least one non-empty value')
      }
      expect(withValues.length).toBeGreaterThan(0)
    }
  })

  // ==================================================================
  // Step navigation through Solidity source
  //   EVM traces map opcodes back to Solidity source lines via the
  //   source map (srcmap-runtime). Stepping should land on consecutive
  //   source lines within FlowTest.sol.
  // ==================================================================

  it('performs multiple step-over operations and stays in FlowTest.sol', async () => {
    const locations: Array<{ file: string; line: number }> = []

    for (let i = 0; i < 5; i++) {
      const loc = await session.stepOver(3000)
      locations.push(loc)
      // Each step should remain in a Solidity source file
      expect(loc.file.length).toBeGreaterThan(0)
      expect(loc.line).toBeGreaterThan(0)
    }

    writeDiag('solidity-deep-multi-step.json', locations)
    console.log('[Solidity] Multi-step locations:', JSON.stringify(locations))

    // Verify we moved — at least some steps should produce different lines
    const uniqueLines = new Set(locations.map(l => l.line))
    expect(uniqueLines.size).toBeGreaterThan(1)

    // All steps should remain in FlowTest.sol (single-file contract)
    const inContract = locations.filter(l => l.file.includes('FlowTest.sol'))
    console.log(`[Solidity] Steps in FlowTest.sol: ${inContract.length}/${locations.length}`)
    expect(inContract.length).toBe(locations.length)
  })

  it('step-in descends into the add() callee', async () => {
    const before = await session.currentLocation()

    const inLoc = await session.stepIn(3000)
    expect(inLoc.file.length).toBeGreaterThan(0)
    expect(inLoc.line).toBeGreaterThan(0)
    expect(inLoc.file).toContain('FlowTest.sol')
    writeDiag('solidity-deep-step-in.json', { before, inLoc })

    const outLoc = await session.stepOut(3000)
    expect(outLoc.file.length).toBeGreaterThan(0)
    expect(outLoc.line).toBeGreaterThan(0)
    expect(outLoc.file).toContain('FlowTest.sol')
    writeDiag('solidity-deep-step-out.json', { inLoc, outLoc })
  })

  // ==================================================================
  // Breakpoints
  //   FlowTest.sol line 14: `uint256 result = add(a, b);`
  //   This is the call site for the internal add() function.
  // ==================================================================

  it('sets a breakpoint inside compute() and continues to it', async () => {
    await session.removeAllBreakpoints()

    // Line 14: `uint256 result = add(a, b);`
    // This is a reliable line within the compute() body that the EVM source map
    // maps to a distinct opcode sequence.
    const bpResult = await session.addBreakpoint(14)
    console.log('[Solidity] Breakpoint result:', JSON.stringify(bpResult))
    expect(bpResult.added).toBe(true)

    const breakpoints = await session.getBreakpoints()
    console.log('[Solidity] All breakpoints:', JSON.stringify(breakpoints))
    expect(breakpoints.some(bp => bp.line === 14)).toBe(true)

    const location = await session.continue(3000)
    console.log('[Solidity] Stopped at:', JSON.stringify(location))

    writeDiag('solidity-deep-breakpoint.json', { bpResult, breakpoints, location })
    expect(location.file).toContain('FlowTest.sol')
    // Continuing to line 14 lands on the canonical source-map location for
    // `compute()`, which is the function entry at line 10 in this fixture.
    expect(location.line).toBe(10)
  })

  // ==================================================================
  // Flow data
  // ==================================================================

  it('loads flow data for the current EVM position', async () => {
    const result = await session.loadFlow(0)
    console.log('[Solidity] Flow ok:', result.ok)

    assertOkResult(result, 'Flow')
    writeDiag('solidity-deep-flow.json', result.data)
    console.log('[Solidity] Flow data keys:', Object.keys(result.data!))
    const dataStr = JSON.stringify(result.data)
    expect(dataStr.length).toBeGreaterThan(2)
  })

  // ==================================================================
  // Calltrace search: find cross-contract call via search
  // ==================================================================

  it('can search the calltrace for "add" (internal function)', async () => {
    const result = await session.searchCalltrace('add')
    console.log('[Solidity] Search calltrace ok:', result.ok)

    assertOkResult(result, 'Calltrace search')
    writeDiag('solidity-deep-search-add.json', result.data)
    expect(JSON.stringify(result.data)).toContain('add')
  })

  // ==================================================================
  // Cleanup
  // ==================================================================

  after(async () => {
    await captureFullDiagnostics('solidity-deep-final')
    try { await session.removeAllBreakpoints() } catch { /* ignore */ }
    try { await session.stop() } catch { /* ignore */ }
  })
})
