/**
 * Deep Solidity (EVM) trace tests for the CodeTracer VS Code extension.
 *
 * Verifies EVM-specific debugging features using the FlowTest.sol fixture:
 *   - Storage variable inspection (storedA, storedResult)
 *   - Solidity event log display (Computed event)
 *   - Internal function call visualization (compute → add)
 *   - Step navigation through Solidity source lines
 *   - Breakpoint placement at a specific contract line
 *
 * The fixture traces the FlowTest.compute() call which:
 *   1. Assigns uint256 a = 10, b = 20
 *   2. Writes storedA = a  (SSTORE opcode)
 *   3. Calls the internal add(a, b) helper
 *   4. Writes storedResult = result  (SSTORE opcode)
 *   5. Emits Computed(result)  (LOG1 opcode)
 *   6. Returns result (= 30)
 *
 * Source: codetracer-evm-recorder/contracts/FlowTest.sol
 * Fixture: generated by scripts/prepare-solidity-fixture.sh
 */
import { expect } from '@wdio/globals'
import { DebugSession, EditorPane, ExtensionState } from '../../page-objects'
import { captureFullDiagnostics, screenshot, writeDiag } from '../../helpers/diagnostics'
import { resolveTracePath, traceExists } from '../../helpers/trace-utils'

const TRACE_NAME = 'solidity-flow-test'

// ---- Known trace data (FlowTest.sol compute() call) ----
// These values come from the contract source and EVM execution.
// See: codetracer-evm-recorder/contracts/FlowTest.sol
const KNOWN_FUNCTIONS = ['compute', 'add']
const KNOWN_STORAGE_VARS = ['storedA', 'storedResult']
// The Computed event is defined as: event Computed(uint256 result)
const KNOWN_EVM_EVENTS = ['Computed']
// Local variables in compute(): a, b, result
const KNOWN_LOCALS = ['a', 'b', 'result']

const session = new DebugSession()
const editor = new EditorPane()
const ext = new ExtensionState()

describe('CodeTracer Extension - Solidity EVM Deep Test', () => {
  let traceDir: string

  before(function () {
    traceDir = resolveTracePath(TRACE_NAME)
    if (!traceExists(TRACE_NAME)) {
      const message =
        `Solidity deep tests: trace not found at ${traceDir}\n` +
        'Run scripts/prepare-solidity-fixture.sh to generate it.\n' +
        'Requires: solc, anvil, cargo, and codetracer-evm-recorder repo as a sibling.'
      console.warn(`SKIPPING ${message}`)
      this.skip()
    }
  })

  afterEach(async function () {
    const testName = this.currentTest?.title?.replace(/[^a-zA-Z0-9_-]+/g, '-').substring(0, 50) ?? 'unknown'
    if (this.currentTest?.state === 'failed') {
      console.log(`[diag] Test failed: ${this.currentTest.title}`)
      await captureFullDiagnostics(`solidity-deep-FAIL-${testName}`)
    }
    await screenshot(`solidity-deep-${testName}`)
  })

  // ==================================================================
  // Session lifecycle
  // ==================================================================

  it('starts a debug session with the Solidity EVM trace', async () => {
    await ext.ensureActivated()
    const started = await session.start(traceDir)
    expect(started).toBe(true)

    const active = await session.isActive()
    expect(active).toBe(true)

    const location = await session.currentLocation()
    console.log('[Solidity] Initial location:', JSON.stringify(location))
    writeDiag('solidity-session-start.json', { started, active, location })
  })

  it('opens FlowTest.sol in the editor', async () => {
    // The debugger should open FlowTest.sol when the trace starts.
    const hasTab = await editor.hasOpenTab('FlowTest.sol')
    if (!hasTab) {
      await browser.waitUntil(
        async () => editor.hasOpenTab('FlowTest.sol'),
        { timeout: 15000, timeoutMsg: 'FlowTest.sol tab did not open within 15s' },
      )
    }

    // Bring FlowTest.sol into focus so subsequent editor assertions work.
    await browser.executeWorkbench(async (vscode) => {
      for (const group of vscode.window.tabGroups.all) {
        for (const tab of group.tabs) {
          const input = tab.input as any
          if (input?.uri?.fsPath?.endsWith('FlowTest.sol')) {
            await vscode.window.showTextDocument(input.uri)
            return
          }
        }
      }
    })
    await browser.pause(1000)

    const state = await editor.state()
    expect(state).not.toBeNull()
    expect(state!.fileName).toContain('FlowTest.sol')
    writeDiag('solidity-editor-state.json', state)
  })

  it('shows Solidity source with pragma and contract definitions', async () => {
    const source = await editor.getText()
    expect(source.length).toBeGreaterThan(0)

    // Verify the contract structure is present in source
    expect(source).toContain('pragma solidity')
    expect(source).toContain('contract FlowTest')
    expect(source).toContain('function compute')
    expect(source).toContain('function add')

    console.log('[Solidity] Source length:', source.length)
    writeDiag('solidity-source-content.txt', source.substring(0, 3000))
  })

  // ==================================================================
  // DAP threads
  // ==================================================================

  it('reports at least one DAP thread', async () => {
    const result = await session.getThreads()
    expect(result.ok).toBe(true)
    expect(result.data!.threads.length).toBeGreaterThanOrEqual(1)
    console.log('[Solidity] Threads:', JSON.stringify(result.data!.threads))
    writeDiag('solidity-threads.json', result.data)
  })

  // ==================================================================
  // Calltrace: cross-contract call visualization
  //   compute() → add()  (internal call, both in FlowTest.sol)
  // ==================================================================

  it('calltrace contains compute() and its internal add() callee', async () => {
    const result = await session.loadCalltrace({ depth: 50, height: 200 })
    console.log('[Solidity] Calltrace ok:', result.ok)

    if (result.ok && result.data) {
      const dataStr = JSON.stringify(result.data)
      writeDiag('solidity-calltrace.json', result.data)

      // Verify the primary function names appear in the calltrace
      const foundFunctions = KNOWN_FUNCTIONS.filter(fn => dataStr.includes(fn))
      console.log('[Solidity] Calltrace functions found:', foundFunctions)

      if (foundFunctions.length > 0) {
        expect(foundFunctions.length).toBeGreaterThan(0)
      }

      // Specifically check for the compute → add call hierarchy
      const hasCompute = dataStr.includes('compute')
      const hasAdd = dataStr.includes('add')
      console.log(`[Solidity] compute=${hasCompute}, add=${hasAdd}`)
    } else {
      console.warn('[Solidity] Calltrace did not return inline data:', result.error)
    }
  })

  // ==================================================================
  // Event log: Solidity event display
  //   The trace should contain the Computed(result) event emitted by
  //   the contract's `emit Computed(result)` statement (LOG1 opcode).
  // ==================================================================

  it('event log contains the Computed(uint256) Solidity event', async () => {
    const result = await session.loadEvents()
    console.log('[Solidity] Events ok:', result.ok)

    if (result.ok && result.data) {
      const dataStr = JSON.stringify(result.data)
      writeDiag('solidity-events.json', result.data)

      const foundEvents = KNOWN_EVM_EVENTS.filter(ev => dataStr.includes(ev))
      console.log('[Solidity] EVM events found:', foundEvents)

      if (foundEvents.length > 0) {
        expect(foundEvents.length).toBeGreaterThan(0)
      }
    } else {
      console.warn('[Solidity] Events did not return inline data:', result.error)
    }
  })

  // ==================================================================
  // Storage variable inspection
  //   EVM-specific: Solidity state variables map to storage slots.
  //   storedA  → slot 0  (written by `storedA = a`)
  //   storedResult → slot 1  (written by `storedResult = result`)
  // ==================================================================

  it('local variables include EVM storage-backed state vars (storedA, storedResult)', async () => {
    const result = await session.loadLocals({ lang: 'Solidity', countBudget: 100, depthLimit: 3 })
    console.log('[Solidity] Locals ok:', result.ok)

    if (result.ok && result.data) {
      const dataStr = JSON.stringify(result.data)
      writeDiag('solidity-locals.json', result.data)

      // Check for Solidity local variables from compute()
      const foundLocals = KNOWN_LOCALS.filter(v => dataStr.includes(v))
      console.log('[Solidity] Locals found:', foundLocals)

      // Also check for storage variable names
      const foundStorage = KNOWN_STORAGE_VARS.filter(v => dataStr.includes(v))
      console.log('[Solidity] Storage vars found:', foundStorage)

      if (result.data.locals && Array.isArray(result.data.locals)) {
        console.log('[Solidity] Total locals:', result.data.locals.length)
        for (const local of result.data.locals.slice(0, 10)) {
          console.log(
            `  ${local.name ?? local.variable_name}: ` +
            JSON.stringify(local).substring(0, 120),
          )
        }

        // At least some variables should have non-empty values
        const withValues = result.data.locals.filter(
          (l: any) => l.value !== undefined && l.value !== null && String(l.value).length > 0,
        )
        console.log(`[Solidity] Locals with values: ${withValues.length}/${result.data.locals.length}`)
      }
    } else {
      console.warn('[Solidity] Locals did not return inline data:', result.error)
    }
  })

  // ==================================================================
  // Step navigation through Solidity source
  //   EVM traces map opcodes back to Solidity source lines via the
  //   source map (srcmap-runtime). Stepping should land on consecutive
  //   source lines within FlowTest.sol.
  // ==================================================================

  it('performs multiple step-over operations and stays in FlowTest.sol', async () => {
    const locations: Array<{ file: string; line: number }> = []

    for (let i = 0; i < 5; i++) {
      const loc = await session.stepOver(3000)
      locations.push(loc)
      // Each step should remain in a Solidity source file
      expect(loc.file.length).toBeGreaterThan(0)
      expect(loc.line).toBeGreaterThan(0)
    }

    writeDiag('solidity-deep-multi-step.json', locations)
    console.log('[Solidity] Multi-step locations:', JSON.stringify(locations))

    // Verify we moved — at least some steps should produce different lines
    const uniqueLines = new Set(locations.map(l => l.line))
    expect(uniqueLines.size).toBeGreaterThan(1)

    // All steps should remain in FlowTest.sol (single-file contract)
    const inContract = locations.filter(l => l.file.includes('FlowTest.sol'))
    console.log(`[Solidity] Steps in FlowTest.sol: ${inContract.length}/${locations.length}`)
    expect(inContract.length).toBeGreaterThan(0)
  })

  it('step-in descends into the add() callee', async () => {
    const before = await session.currentLocation()

    const inLoc = await session.stepIn(3000)
    expect(inLoc.file.length).toBeGreaterThan(0)
    expect(inLoc.line).toBeGreaterThan(0)
    writeDiag('solidity-deep-step-in.json', { before, inLoc })

    const outLoc = await session.stepOut(3000)
    expect(outLoc.file.length).toBeGreaterThan(0)
    expect(outLoc.line).toBeGreaterThan(0)
    writeDiag('solidity-deep-step-out.json', { inLoc, outLoc })
  })

  // ==================================================================
  // Breakpoints
  //   FlowTest.sol line 14: `uint256 result = add(a, b);`
  //   This is the call site for the internal add() function.
  // ==================================================================

  it('sets a breakpoint inside compute() and continues to it', async () => {
    await session.removeAllBreakpoints()

    // Line 14: `uint256 result = add(a, b);`
    // This is a reliable line within the compute() body that the EVM source map
    // maps to a distinct opcode sequence.
    const bpResult = await session.addBreakpoint(14)
    console.log('[Solidity] Breakpoint result:', JSON.stringify(bpResult))
    expect(bpResult.added).toBe(true)

    const breakpoints = await session.getBreakpoints()
    console.log('[Solidity] All breakpoints:', JSON.stringify(breakpoints))
    expect(breakpoints.some(bp => bp.line === 14)).toBe(true)

    const location = await session.continue(3000)
    console.log('[Solidity] Stopped at:', JSON.stringify(location))

    writeDiag('solidity-deep-breakpoint.json', { bpResult, breakpoints, location })
  })

  // ==================================================================
  // Flow data
  // ==================================================================

  it('loads flow data for the current EVM position', async () => {
    const result = await session.loadFlow(0)
    console.log('[Solidity] Flow ok:', result.ok)

    if (result.ok && result.data) {
      writeDiag('solidity-deep-flow.json', result.data)
      console.log('[Solidity] Flow data keys:', Object.keys(result.data))
      const dataStr = JSON.stringify(result.data)
      expect(dataStr.length).toBeGreaterThan(2)
    } else {
      console.warn('[Solidity] Flow did not return inline data:', result.error)
    }
  })

  // ==================================================================
  // Calltrace search: find cross-contract call via search
  // ==================================================================

  it('can search the calltrace for "add" (internal function)', async () => {
    const result = await session.searchCalltrace('add')
    console.log('[Solidity] Search calltrace ok:', result.ok)

    if (result.ok && result.data) {
      writeDiag('solidity-deep-search-add.json', result.data)
    }
  })

  // ==================================================================
  // Cleanup
  // ==================================================================

  after(async () => {
    await captureFullDiagnostics('solidity-deep-final')
    try { await session.removeAllBreakpoints() } catch { /* ignore */ }
    try { await session.stop() } catch { /* ignore */ }
  })
})
