/**
 * Stylus trace integration tests for the CodeTracer VS Code extension.
 *
 * These tests load a pre-recorded Stylus (Arbitrum WASM) trace fixture and
 * verify the full debugging experience: source code in the editor, calltrace,
 * event log, local variables, breakpoints, step operations, and flow data.
 *
 * The fixture is generated by `scripts/prepare-stylus-fixture.sh` or by
 * running `STYLUS_FIXTURE_OUTPUT_DIR=<path> just test-stylus-flow-full`
 * in the codetracer repo.
 */
import path from 'path'
import fs from 'fs'
import { browser, expect } from '@wdio/globals'
import { DebugSession, EditorPane, ExtensionState } from '../../page-objects'
import { getPanelStatus, inspectWebviews } from '../../page-objects/panels'
import { captureFullDiagnostics, screenshot, writeDiag } from '../../helpers/diagnostics'
import * as dap from '../../helpers/dap-client'

// ---- Fixture path resolution ----

const FIXTURE_DIR = path.resolve(__dirname, '..', '..', '..', 'fixtures', 'stylus-fund-trace')

function fixtureExists(): boolean {
  const ctFiles = fs.existsSync(FIXTURE_DIR)
    ? fs.readdirSync(FIXTURE_DIR).some(name => name.endsWith('.ct'))
    : false
  const traceJson = path.join(FIXTURE_DIR, 'trace.json')
  const traceBin = path.join(FIXTURE_DIR, 'trace.bin')
  const traceMetadata = path.join(FIXTURE_DIR, 'trace_metadata.json')
  return ctFiles || ((fs.existsSync(traceJson) || fs.existsSync(traceBin)) && fs.existsSync(traceMetadata))
}

// ---- Page object instances ----

const session = new DebugSession()
const editor = new EditorPane()
const ext = new ExtensionState()

// ---- Known trace data ----
// The fixture trace contains these functions, step lines, variables, and events.
// See: codetracer/src/db-backend/tests/stylus_flow_integration.rs

const KNOWN_FUNCTIONS = ['new', 'vm', 'deny_value', 'fund', '__stylus_struct_entrypoint', 'user_entrypoint']
const VALID_STEP_LINES = [38, 45, 49, 58, 59, 60, 61, 62]
const KNOWN_VARIABLES = ['root', 'offset', 'host', 'self', 'method_name', 'pari', 'new_fund', 'input', 'len']
const KNOWN_EVM_EVENTS = ['read_args', 'storage_load', 'storage_cache', 'native_keccak256', 'write_result']

// ---- Test suite ----

describe('CodeTracer Extension - Stylus Trace Loading', () => {
  before(function () {
    if (!fixtureExists()) {
      const message =
        `Stylus trace tests: fixture not found at ${FIXTURE_DIR}\n` +
        'Run scripts/prepare-stylus-fixture.sh to generate it.'
      throw new Error(message)
    }
  })

  afterEach(async function () {
    const testName = this.currentTest?.title?.replace(/[^a-zA-Z0-9_-]+/g, '-').substring(0, 50) ?? 'unknown'
    if (this.currentTest?.state === 'failed') {
      console.log(`[diag] Test failed: ${this.currentTest.title}`)
      await captureFullDiagnostics(`stylus-FAIL-${testName}`)
      await inspectWebviews(`fail-${testName}`)
    }
    // Always capture a screenshot for the trace (useful for visual verification)
    await screenshot(`stylus-${testName}`)
  })

  // ==================================================================
  // Session lifecycle
  // ==================================================================

  it('starts a debug session with the Stylus trace', async () => {
    // Ensure extension is active before starting a debug session
    await ext.ensureActivated()

    const started = await session.start(FIXTURE_DIR)
    expect(started).toBe(true)

    const active = await session.isActive()
    expect(active).toBe(true)

    // Capture initial session state for diagnostics
    const location = await session.currentLocation()
    console.log('Initial location:', JSON.stringify(location))
    writeDiag('session-start.json', { started, active, location })
  })

  // ==================================================================
  // Source code in editor
  // ==================================================================

  it('opens the contract source file (lib.rs) in the editor', async () => {
    // The debugger opens lib.rs in a tab but may not make it the active editor
    // immediately. First verify it's in the open tabs, then try to activate it.
    const hasLib = await editor.hasOpenTab('lib.rs')
    if (!hasLib) {
      // Wait longer for the tab to appear
      await browser.waitUntil(
        async () => editor.hasOpenTab('lib.rs'),
        { timeout: 15000, timeoutMsg: 'lib.rs tab did not open within 15s' }
      )
    }

    // Activate lib.rs by opening it via VS Code command
    await browser.executeWorkbench(async (vscode) => {
      const tabs = []
      for (const group of vscode.window.tabGroups.all) {
        for (const tab of group.tabs) {
          const input = tab.input as any
          if (input?.uri?.fsPath?.endsWith('lib.rs')) {
            // Focus this tab by opening its URI
            await vscode.window.showTextDocument(input.uri)
            return
          }
        }
      }
    })

    await browser.pause(1000)

    const editorState = await editor.state()
    console.log('Editor state after activation:', JSON.stringify(editorState))
    expect(editorState).not.toBeNull()
    expect(editorState!.fileName).toContain('lib.rs')
  })

  it('shows Stylus contract source code with sol_storage! and fund()', async () => {
    // Ensure lib.rs is the active editor (may have been set by previous test)
    const state = await editor.state()
    if (!state?.fileName?.includes('lib.rs')) {
      // Try to activate it
      await browser.executeWorkbench(async (vscode) => {
        for (const group of vscode.window.tabGroups.all) {
          for (const tab of group.tabs) {
            const input = tab.input as any
            if (input?.uri?.fsPath?.endsWith('lib.rs')) {
              await vscode.window.showTextDocument(input.uri)
              return
            }
          }
        }
      })
      await browser.pause(1000)
    }

    const source = await editor.getText()
    expect(source.length).toBeGreaterThan(0)

    // The source must contain the Stylus sol_storage! macro definition
    expect(source).toContain('sol_storage!')

    // The source must contain the fund() method we're testing
    expect(source).toContain('fn fund')

    // Verify specific lines that the trace references
    // Line 59: `let mut new_fund = self.funds.grow();`
    const line59 = await editor.getLine(59)
    console.log('Line 59:', line59)
    expect(line59).toContain('new_fund')

    writeDiag('source-content.txt', source.substring(0, 5000))
  })

  // ==================================================================
  // File explorer: open editor tabs show trace source files
  // ==================================================================

  it('has lib.rs among the open editor tabs', async () => {
    const hasLib = await editor.hasOpenTab('lib.rs')
    expect(hasLib).toBe(true)

    const tabs = await editor.openTabs()
    console.log('Open tabs:', tabs)
    writeDiag('open-tabs.json', tabs)
  })

  // ==================================================================
  // DAP threads
  // ==================================================================

  it('reports at least one DAP thread', async () => {
    const result = await session.getThreads()
    expect(result.ok).toBe(true)
    expect(result.data!.threads.length).toBeGreaterThanOrEqual(1)
    console.log('Threads:', JSON.stringify(result.data!.threads))
    writeDiag('dap-threads.json', result.data)
  })

  // ==================================================================
  // Calltrace: the trace should contain fund() and its callees
  // ==================================================================

  it('loads a calltrace with known Stylus functions', async () => {
    const result = await session.loadCalltrace({ depth: 50, height: 200 })
    console.log('Calltrace response ok:', result.ok)

    expect(result.ok).toBe(true)
    expect(result.data).toBeDefined()
    const dataStr = JSON.stringify(result.data)
    console.log('Calltrace data keys:', Object.keys(result.data!))
    writeDiag('dap-calltrace.json', result.data)

    const foundFunctions = KNOWN_FUNCTIONS.filter(fn => dataStr.includes(fn))
    console.log('Found functions in calltrace:', foundFunctions)
    expect(foundFunctions.length).toBeGreaterThan(0)
  })

  // ==================================================================
  // Event log: EVM host function events
  // ==================================================================

  it('loads EVM events from the Stylus trace', async () => {
    const result = await session.loadEvents()
    console.log('Event load response ok:', result.ok)

    expect(result.ok).toBe(true)
    expect(result.data).toBeDefined()
    const dataStr = JSON.stringify(result.data)
    writeDiag('dap-events.json', result.data)

    const foundEvents = KNOWN_EVM_EVENTS.filter(ev => dataStr.includes(ev))
    console.log('Found EVM events:', foundEvents)
    expect(foundEvents.length).toBeGreaterThan(0)
  })

  // ==================================================================
  // State window: local variables at the current position
  // ==================================================================

  it('can load local variables including trace-specific names', async () => {
    const result = await session.loadLocals({ lang: 'Rust', countBudget: 100, depthLimit: 3 })
    console.log('Load locals response ok:', result.ok)

    expect(result.ok).toBe(true)
    expect(result.data).toBeDefined()
    writeDiag('dap-locals.json', result.data)

    const dataStr = JSON.stringify(result.data)
    const foundVars = KNOWN_VARIABLES.filter(v => dataStr.includes(v))
    console.log('Found variables:', foundVars)
    expect(foundVars.length).toBeGreaterThan(0)

    if (result.data!.locals && Array.isArray(result.data!.locals)) {
      console.log('Locals count:', result.data!.locals.length)
      for (const local of result.data!.locals.slice(0, 10)) {
        console.log(`  ${local.name ?? local.variable_name}: ${JSON.stringify(local).substring(0, 120)}`)
      }
    }
  })

  // ==================================================================
  // Step operations: step-over should move to a valid trace line
  // ==================================================================

  it('can step-over and land on a valid trace line', async () => {
    const before = await session.currentLocation()
    console.log('Before step:', JSON.stringify(before))

    const after = await session.stepOver(2000)
    console.log('After step:', JSON.stringify(after))

    // After stepping, we should still be in lib.rs
    expect(after.file).toContain('lib.rs')

    // The new line should be one of the known step positions in the trace
    expect(VALID_STEP_LINES).toContain(after.line)

    writeDiag('step-over.json', { before, after })
  })

  it('can step-in and remain in the trace', async () => {
    const before = await session.currentLocation()
    const after = await session.stepIn(2000)
    console.log('Step-in:', JSON.stringify({ before, after }))

    // We should still be in a source file (lib.rs or possibly a callee)
    expect(after.file.length).toBeGreaterThan(0)
    expect(after.line).toBeGreaterThan(0)

    writeDiag('step-in.json', { before, after })
  })

  // ==================================================================
  // Breakpoints: set at line 59 and continue to it
  // ==================================================================

  it('can set a breakpoint at line 59 (inside fund()) and continue to it', async () => {
    // Remove any existing breakpoints first
    await session.removeAllBreakpoints()

    // Line 59: `let mut new_fund = self.funds.grow();`
    const bpResult = await session.addBreakpoint(59)
    console.log('Breakpoint result:', JSON.stringify(bpResult))
    expect(bpResult.total).toBeGreaterThanOrEqual(1)
    expect(bpResult.added).toBe(true)

    // Verify the breakpoint is in the list
    const breakpoints = await session.getBreakpoints()
    console.log('All breakpoints:', JSON.stringify(breakpoints))
    expect(breakpoints.some(bp => bp.line === 59)).toBe(true)

    // Continue execution to hit the breakpoint
    const location = await session.continue(3000)
    console.log('Stopped at:', JSON.stringify(location))

    // For offline traces, breakpoint behavior may differ from live debugging.
    // Log the result for diagnostic purposes rather than asserting exact line.
    writeDiag('breakpoint-continue.json', { bpResult, breakpoints, location })
  })

  // ==================================================================
  // Flow data
  // ==================================================================

  it('can load flow data for the current location', async () => {
    const result = await session.loadFlow(0)
    console.log('Flow load response ok:', result.ok)

    expect(result.ok).toBe(true)
    expect(result.data).toBeDefined()
    writeDiag('dap-flow.json', result.data)
    console.log('Flow data keys:', Object.keys(result.data!))
  })

  // ==================================================================
  // Terminal output
  // ==================================================================

  it('can load terminal output from the trace', async () => {
    const result = await session.loadTerminal()
    console.log('Terminal load response ok:', result.ok)

    if (result.ok && result.data) {
      writeDiag('dap-terminal.json', result.data)
    }
  })

  // ==================================================================
  // Panels: verify CodeTracer panels exist
  // ==================================================================

  it('has CodeTracer panels registered in VS Code', async () => {
    const panels = await getPanelStatus()
    console.log('Panel status:', JSON.stringify(panels))
    writeDiag('panel-status.json', panels)

    // Even if panels aren't visible (they may be in inactive tab groups),
    // the tab groups API should show that webview panels were created.
    // Note: in some configurations, panels are opened on-demand via commands.
  })

  // ==================================================================
  // Context key: codetracer:active should be set
  // ==================================================================

  it('has an active CodeTracer debug session (codetracer:active)', async () => {
    const active = await session.isActive()
    expect(active).toBe(true)
  })

  // ==================================================================
  // Calltrace search
  // ==================================================================

  it('can search the calltrace for "fund"', async () => {
    const result = await session.searchCalltrace('fund')
    console.log('Search calltrace result:', result.ok)

    if (result.ok && result.data) {
      writeDiag('dap-search-fund.json', result.data)
    }
  })

  // ==================================================================
  // Cleanup
  // ==================================================================

  after(async () => {
    // Capture final diagnostic state
    await captureFullDiagnostics('stylus-final')
    await inspectWebviews('final')

    // Remove breakpoints and stop session
    try { await session.removeAllBreakpoints() } catch { /* ignore */ }
    try { await session.stop() } catch { /* ignore */ }
  })
})
