/**
 * Deep Tolk (TON) trace tests for the CodeTracer VS Code extension.
 *
 * Extends the smoke test coverage with:
 *   - Variable VALUE assertions (not just name existence)
 *   - Multi-step navigation with line change verification
 *   - Breakpoint placement and continue-to-breakpoint
 *   - Step-in / step-out navigation
 *   - Calltrace function verification
 *
 * The fixture trace is generated by scripts/prepare-tolk-fixture.sh and
 * records the flow_test.tolk program which performs stack-based TVM operations
 * in the Tolk/TON VM tracer.
 *
 * Source: codetracer-tolk-recorder/test-programs/tolk/flow_test.tolk
 */
import { browser, expect } from '@wdio/globals'
import { DebugSession, EditorPane, ExtensionState } from '../../page-objects'
import { captureFullDiagnostics, screenshot, writeDiag } from '../../helpers/diagnostics'
import { resolveTracePath, traceExists } from '../../helpers/trace-utils'

const TRACE_NAME = 'tolk-flow-test'

// ---- Known trace data (flow_test.tolk) ----
// The compute function performs stack-based arithmetic. The TVM stack-based
// execution model exposes locals as debugging variables.
const KNOWN_FUNCTIONS = ['compute']
const KNOWN_VARIABLE = 'a'

const session = new DebugSession()
const editor = new EditorPane()
const ext = new ExtensionState()

describe('CodeTracer Extension - Tolk (TON) Deep Test', () => {
  let traceDir: string

  before(function () {
    traceDir = resolveTracePath(TRACE_NAME)
    if (!traceExists(TRACE_NAME)) {
      const message =
        `Tolk deep tests: trace not found at ${traceDir}\n` +
        'Run scripts/prepare-tolk-fixture.sh to generate it.'
      if (process.env.CI === 'true' || !!process.env.GITHUB_ACTIONS) {
        throw new Error(message)
      }
      console.warn(`SKIPPING ${message}`)
      this.skip()
    }
  })

  afterEach(async function () {
    const testName = this.currentTest?.title?.replace(/\s+/g, '-').substring(0, 50) ?? 'unknown'
    if (this.currentTest?.state === 'failed') {
      console.log(`[diag] Test failed: ${this.currentTest.title}`)
      await captureFullDiagnostics(`tolk-deep-FAIL-${testName}`)
    }
    await screenshot(`tolk-deep-${testName}`)
  })

  // ==================================================================
  // Session lifecycle
  // ==================================================================

  it('starts a debug session with the Tolk trace', async () => {
    await ext.ensureActivated()
    const started = await session.start(traceDir)
    expect(started).toBe(true)

    const active = await session.isActive()
    expect(active).toBe(true)

    const location = await session.currentLocation()
    console.log('[Tolk] Initial location:', JSON.stringify(location))
    writeDiag('tolk-session-start.json', { started, active, location })
  })

  // ==================================================================
  // Editor: verify flow_test.tolk opens
  // ==================================================================

  it('opens flow_test.tolk in the editor', async () => {
    const hasTab = await editor.hasOpenTab('flow_test.tolk')
    if (!hasTab) {
      await browser.waitUntil(
        async () => editor.hasOpenTab('flow_test.tolk'),
        { timeout: 15000, timeoutMsg: 'flow_test.tolk tab did not open within 15s' },
      )
    }

    // Activate the tab so subsequent checks work against it.
    await browser.executeWorkbench(async (vscode) => {
      for (const group of vscode.window.tabGroups.all) {
        for (const tab of group.tabs) {
          const input = tab.input as any
          if (input?.uri?.fsPath?.endsWith('flow_test.tolk')) {
            await vscode.window.showTextDocument(input.uri)
            return
          }
        }
      }
    })
    await browser.pause(1000)

    const state = await editor.state()
    expect(state).not.toBeNull()
    expect(state!.fileName).toContain('flow_test.tolk')
    writeDiag('tolk-editor-state.json', state)
  })

  // ==================================================================
  // DAP threads
  // ==================================================================

  it('reports at least one DAP thread', async () => {
    const result = await session.getThreads()
    expect(result.ok).toBe(true)
    expect(result.data!.threads.length).toBeGreaterThanOrEqual(1)
    console.log('[Tolk] Threads:', JSON.stringify(result.data!.threads))
    writeDiag('tolk-threads.json', result.data)
  })

  // ==================================================================
  // Calltrace: verify compute function appears
  // ==================================================================

  it('calltrace contains the compute function', async () => {
    const result = await session.loadCalltrace({ depth: 50, height: 200 })
    expect(result.ok).toBe(true)
    writeDiag('tolk-calltrace.json', result.data)

    const dataStr = JSON.stringify(result.data)
    const foundFunctions = KNOWN_FUNCTIONS.filter(fn => dataStr.includes(fn))
    console.log('[Tolk] Calltrace functions found:', foundFunctions)
    expect(dataStr).toContain('compute')
  })

  // ==================================================================
  // Events: verify event log is populated
  // ==================================================================

  it('loads events from the trace', async () => {
    const result = await session.loadEvents()
    console.log('[Tolk] Events ok:', result.ok)

    expect(result.ok).toBe(true)

    if (result.data) {
      const dataStr = JSON.stringify(result.data)
      writeDiag('tolk-events.json', result.data)
      // Events should have some content (more than an empty object)
      expect(dataStr.length).toBeGreaterThan(2)
    }
  })

  // ==================================================================
  // Locals: verify variable values (not just names)
  // ==================================================================

  it('loads locals with variable values including a', async () => {
    // The initial position is at main() which just calls compute(). Step into
    // compute() and advance past variable assignments so locals are populated.
    const stepInLoc = await session.stepIn(3000)
    console.log('[Tolk] Stepped into:', JSON.stringify(stepInLoc))
    for (let i = 0; i < 3; i++) {
      const loc = await session.stepOver(2000)
      console.log(`[Tolk] Step ${i + 1}:`, JSON.stringify(loc))
    }

    const result = await session.loadLocals({ lang: 'Tolk', countBudget: 100, depthLimit: 3 })
    expect(result.ok).toBe(true)
    writeDiag('tolk-deep-locals.json', result.data)

    if (result.data) {
      const dataStr = JSON.stringify(result.data)
      // Verify the known variable name is present
      expect(dataStr).toContain(KNOWN_VARIABLE)

      // Verify at least one variable has a non-empty value
      if (result.data.locals && Array.isArray(result.data.locals)) {
        console.log('[Tolk] Total locals:', result.data.locals.length)

        const withValues = result.data.locals.filter(
          (l: any) => l.value !== undefined && l.value !== null && String(l.value).length > 0,
        )
        console.log(`[Tolk] Locals with values: ${withValues.length}/${result.data.locals.length}`)
        expect(withValues.length).toBeGreaterThan(0)

        // Log first few for diagnostics
        for (const v of withValues.slice(0, 5)) {
          console.log(`  ${v.name ?? v.variable_name}: ${JSON.stringify(v.value).substring(0, 80)}`)
        }
      }
    }
  })

  // ==================================================================
  // Step navigation: multi-step and line change verification
  // ==================================================================

  it('performs multiple step-over operations and changes line', async () => {
    // After the locals test, we should already be inside compute().
    const current = await session.currentLocation()
    console.log('[Tolk] Pre-step location:', JSON.stringify(current))

    const locations: Array<{ file: string; line: number }> = [current]

    for (let i = 0; i < 5; i++) {
      const loc = await session.stepOver(3000)
      locations.push(loc)
      // Each step should land in a source file with a valid line
      expect(loc.file.length).toBeGreaterThan(0)
      expect(loc.line).toBeGreaterThan(0)
    }

    writeDiag('tolk-deep-multi-step.json', locations)
    console.log('[Tolk] Multi-step locations:', JSON.stringify(locations))

    // Verify we actually moved — inside compute(), lines should change.
    const uniqueLines = new Set(locations.map(l => l.line))
    expect(uniqueLines.size).toBeGreaterThan(1)
  })

  it('step-in enters a callee and step-out returns', async () => {
    const before = await session.currentLocation()

    const inLoc = await session.stepIn(3000)
    expect(inLoc.file.length).toBeGreaterThan(0)
    expect(inLoc.line).toBeGreaterThan(0)
    writeDiag('tolk-deep-step-in.json', { before, inLoc })

    const outLoc = await session.stepOut(3000)
    expect(outLoc.file.length).toBeGreaterThan(0)
    expect(outLoc.line).toBeGreaterThan(0)
    writeDiag('tolk-deep-step-out.json', { inLoc, outLoc })
  })

  // ==================================================================
  // Breakpoints: set and continue
  // ==================================================================

  it('sets a breakpoint and continues to it', async () => {
    await session.removeAllBreakpoints()

    // Set breakpoint at an early line in flow_test.tolk. Tolk programs
    // typically have function definitions in the first few lines.
    const bpResult = await session.addBreakpoint(5)
    console.log('[Tolk] Breakpoint result:', JSON.stringify(bpResult))
    expect(bpResult.added).toBe(true)

    const breakpoints = await session.getBreakpoints()
    console.log('[Tolk] All breakpoints:', JSON.stringify(breakpoints))
    expect(breakpoints.some(bp => bp.line === 5)).toBe(true)

    const location = await session.continue(3000)
    console.log('[Tolk] Stopped at:', JSON.stringify(location))

    // After continue, we should be at a valid location
    expect(location.file.length).toBeGreaterThan(0)
    expect(location.line).toBeGreaterThan(0)

    writeDiag('tolk-deep-breakpoint.json', { bpResult, breakpoints, location })
  })

  // ==================================================================
  // Flow data
  // ==================================================================

  it('loads flow data for the current position', async () => {
    const result = await session.loadFlow(0)
    console.log('[Tolk] Flow ok:', result.ok)

    expect(result.ok).toBe(true)

    if (result.data) {
      writeDiag('tolk-deep-flow.json', result.data)
      console.log('[Tolk] Flow data keys:', Object.keys(result.data))
      const dataStr = JSON.stringify(result.data)
      expect(dataStr.length).toBeGreaterThan(2)
    }
  })

  // ==================================================================
  // Calltrace search
  // ==================================================================

  it('can search the calltrace for "compute"', async () => {
    const result = await session.searchCalltrace('compute')
    console.log('[Tolk] Search calltrace ok:', result.ok)
    expect(result.ok).toBe(true)

    if (result.data) {
      writeDiag('tolk-deep-search-compute.json', result.data)
    }
  })

  // ==================================================================
  // Cleanup
  // ==================================================================

  after(async () => {
    await captureFullDiagnostics('tolk-deep-final')
    try { await session.removeAllBreakpoints() } catch { /* ignore */ }
    try { await session.stop() } catch { /* ignore */ }
  })
})
